"""נתוני דמו להדגמת הדוח ללא חיבור לאינטרנט."""

DEMO_STOCKS = [
    {
        "ticker": "IONQ",
        "company_name": "IonQ, Inc.",
        "sector": "Technology",
        "industry": "Quantum Computing",
        "current_price": 12.45,
        "price_52w_high": 48.50,
        "price_52w_low": 8.20,
        "pct_from_52w_high": -74.3,
        "pct_from_ath": -74.3,
        "price_change_1m_pct": -8.2,
        "price_change_3m_pct": -22.1,
        "market_cap": 2_100_000_000,
        "revenue_ttm": 36_000_000,
        "revenue_growth_yoy": 0.98,
        "gross_margin": 0.49,
        "operating_margin": -2.80,
        "net_margin": -2.60,
        "fcf_ttm": -85_000_000,
        "fcf_margin": -0.36,
        "roic": -0.18,
        "roe": -0.45,
        "debt_to_equity": 0.25,
        "current_ratio": 4.2,
        "cash": 350_000_000,
        "eps_ttm": -1.20,
        "eps_growth_yoy": 0.30,
        "rd_expense": 60_000_000,
        "capex": 12_000_000,
        "capex_growth_yoy": 0.45,
        "shares_outstanding": 168_000_000,
        "shares_change_yoy": 0.08,
        "short_interest_pct": 0.18,
        "short_ratio": 3.2,
        "pe_ttm": 0, "pe_forward": 0,
        "ps_ratio": 58.0, "pb_ratio": 3.2,
        "ev_ebitda": 0, "peg_ratio": 0,
        "analyst_consensus": "buy",
        "analyst_target_mean": 22.0,
        "analyst_target_high": 40.0,
        "analyst_target_low": 10.0,
        "analyst_count": 8,
        "avg_volume_30d": 4_500_000,
        "today_volume": 6_200_000,
        "accruals_ratio": 0.05,
        "earnings_quality": "Medium",
        "earnings_flags": ["⚠️ דילול מניות משמעותי"],
        "quality_score_bonus": -0.3,
        "moat_type": "Narrow",
        "moat_sources": ["פטנטים בטכנולוגיית קוונטום", "קשרים עם IBM ו-Amazon"],
        "moat_score": 6.5,
        "moat_durability_years": 7,
        "pricing_power": "Moderate",
        "fundamental_score": 5.0,
        "growth_score": 8.5,
        "valuation_score": 5.5,
        "valuation_vs_sector": "Fair",
        "dcf_rough_range": "$8-25",
        "multibagger_potential": "Very High",
        "multibagger_reason_hebrew": "קוונטום קומפיוטינג היא שוק של טריליון דולר. IonQ עם הטכנולוגיה המובילה ותחת $2B market cap — זו ההזדמנות לפני שהשוק מבין.",
        "years_to_potential_peak": "4-7 שנים",
        "key_strengths_hebrew": ["מובילה בדיוק קוונטום", "שותפויות עם ענקיות הטק", "מאגר מזומנים לשנים"],
        "key_risks_hebrew": ["עדיין לא רווחית", "תחרות מ-IBM, Google", "טכנולוגיה לא בשלה"],
        "growth_drivers_hebrew": ["ענן קוונטום", "ביטחון לאומי", "תרופות ולוגיסטיקה"],
        "sector_verdict_hebrew": "זולה ביחס לפוטנציאל הענפי. רוב המתחרים גדולים פי 10+.",
        "earnings_quality_comment": "שורף מזומנים — נורמלי לשלב זה. אבל 18% short interest מסוכן.",
        "short_squeeze_potential": True,
        "bull_case_hebrew": "קוונטום מגיע בשנות ה-30. IonQ תהיה ה-NVIDIA של הקוונטום.",
        "bear_case_hebrew": "IBM ו-Google מוחקים אותה. מזומנים נגמרים לפני שהמוצר בשל.",
        "psychology_note_hebrew": "ירידה של 74% מהשיא — זה המשחק. אם התזה נכונה, האסימטריה מנצחת.",
        "verdict_hebrew": "⭐ TOP PICK — כניסה ב-DCA. קנה שליש עכשיו, שליש ב-$10, שליש ב-$8.",
        "above_ma50": False, "above_ma200": False,
        "rsi_14": 38.5, "rsi_signal": "Oversold",
        "macd_bullish": False, "bb_pct": 0.12,
        "support_1": 10.80, "support_2": 9.50,
        "resistance_1": 15.20, "high_52w": 48.50,
        "volume_ratio": 1.38,
        "technical_score": 6.2,
        "trend": "Bearish",
        "ma20": 13.1, "ma50": 16.8, "ma200": 24.5,
        "basket": "A",
        "aggressive_invest_score": 7.0,
        "intangible_score": 8.0,
        "sentiment_score": 6.5,
        "total_score": 7.2,
        "action": "✅ צבור הדרגתית",
        "action_color": "green",
        "explanation": "Oversold + פוטנציאל Very High",
        "position_usd": 110,
        "position_note": "$110 — כניסה ראשונית בלבד (10%)",
        "dca_plan": ["כניסה ראשונה: $37 עכשיו @ $12.45", "כניסה שנייה: $37 אם ירד ל-$10.80", "כניסה שלישית: $37 אם ירד ל-$9.50"],
        "entry_now": 12.45, "entry_ideal": 10.91, "entry_patient": 9.69,
        "stop_loss": 9.22, "stop_loss_note": "אם נשבר — צא. לא לנחש.",
        "target_1y": 16.19, "target_3y": 31.13,
        "risk_reward": 0.9, "rr_note": "נמוך מדי",
        "buy_signals": ["RSI 38 — oversold, הזדמנות", "ליד Bollinger התחתון — לחץ מכירה מוגזם"],
        "sell_signals": ["מתחת MA200 — מגמה יורדת"],
        "wait_signals": [],
        "psychology_note": "⚠️ IONQ ירדה 74% מהשיא. זה לא סיבה למכור — זו הסיבה שבדקנו אותה. בדוק: האם התזה המקורית עדיין תקפה?",
    },
    {
        "ticker": "HIMS",
        "company_name": "Hims & Hers Health, Inc.",
        "sector": "Healthcare",
        "industry": "Telehealth",
        "current_price": 18.75,
        "price_52w_high": 72.0,
        "price_52w_low": 14.20,
        "pct_from_52w_high": -74.0,
        "pct_from_ath": -74.0,
        "price_change_1m_pct": 5.2,
        "price_change_3m_pct": -31.0,
        "market_cap": 3_800_000_000,
        "revenue_ttm": 870_000_000,
        "revenue_growth_yoy": 0.67,
        "gross_margin": 0.79,
        "operating_margin": 0.05,
        "net_margin": 0.04,
        "fcf_ttm": 40_000_000,
        "fcf_margin": 0.046,
        "roic": 0.08,
        "roe": 0.12,
        "debt_to_equity": 0.18,
        "current_ratio": 2.8,
        "cash": 200_000_000,
        "eps_ttm": 0.12,
        "eps_growth_yoy": 2.5,
        "rd_expense": 30_000_000,
        "capex": 50_000_000,
        "capex_growth_yoy": 0.35,
        "shares_outstanding": 202_000_000,
        "shares_change_yoy": 0.03,
        "short_interest_pct": 0.22,
        "short_ratio": 4.1,
        "pe_ttm": 156, "pe_forward": 28,
        "ps_ratio": 4.4, "pb_ratio": 6.5,
        "ev_ebitda": 48, "peg_ratio": 0.8,
        "analyst_consensus": "buy",
        "analyst_target_mean": 35.0,
        "analyst_target_high": 55.0,
        "analyst_target_low": 15.0,
        "analyst_count": 12,
        "avg_volume_30d": 8_000_000,
        "today_volume": 11_000_000,
        "accruals_ratio": 0.02,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Narrow",
        "moat_sources": ["מותג חזק", "מנויים חוזרים", "פלטפורמת תרופות מותאמות"],
        "moat_score": 6.8,
        "moat_durability_years": 5,
        "pricing_power": "Strong",
        "fundamental_score": 7.2,
        "growth_score": 8.8,
        "valuation_score": 7.0,
        "valuation_vs_sector": "Undervalued",
        "dcf_rough_range": "$25-50",
        "multibagger_potential": "High",
        "multibagger_reason_hebrew": "טלהלט + תרופות מותאמות = שוק $100B. HIMS בדרך לכבוש אותו עם FCF חיובי ו-79% gross margin.",
        "years_to_potential_peak": "3-5 שנים",
        "key_strengths_hebrew": ["Gross margin 79% — נדיר בביוטק", "FCF חיובי בשנה 5", "צמיחה 67% YoY"],
        "key_risks_hebrew": ["תחרות מ-Roman, Teladoc", "רגולציה FDA על תרופות GLP-1", "Short interest 22%"],
        "growth_drivers_hebrew": ["תרופות לירידה במשקל (GLP-1)", "הרחבה לנשים", "פלטפורמת mental health"],
        "sector_verdict_hebrew": "זול ביחס לביוטק. P/S 4.4 עם 67% צמיחה = ממש אטרקטיבי.",
        "earnings_quality_comment": "FCF חיובי + gross margin 79% = איכות גבוהה מאוד.",
        "short_squeeze_potential": True,
        "bull_case_hebrew": "HIMS הופכת ל-Walmart של תרופות דיגיטליות. $5B revenue ב-2028.",
        "bear_case_hebrew": "FDA מגביל GLP-1 compounding. התחרות מ-Novo Nordisk מוחצת.",
        "psychology_note_hebrew": "74% מהשיא — בדיוק שם נוצרים multibaggers. הפונדמנטלי השתפר, המחיר ירד.",
        "verdict_hebrew": "✅ קנה עכשיו — FCF חיובי, צמיחה אדירה, מחיר אטרקטיבי.",
        "above_ma50": True, "above_ma200": False,
        "rsi_14": 52.3, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.55,
        "support_1": 16.50, "support_2": 14.80,
        "resistance_1": 22.0, "high_52w": 72.0,
        "volume_ratio": 1.37,
        "technical_score": 6.8,
        "trend": "Mixed",
        "ma20": 17.8, "ma50": 17.2, "ma200": 28.4,
        "basket": "A",
        "aggressive_invest_score": 6.5,
        "intangible_score": 6.0,
        "sentiment_score": 7.0,
        "total_score": 7.6,
        "action": "✅ קנה עכשיו",
        "action_color": "green",
        "explanation": "סיגנלים חיוביים + פונדמנטלי חזק",
        "position_usd": 165,
        "position_note": "$165 — כניסה בינונית (15%)",
        "dca_plan": ["כניסה ראשונה: $55 עכשיו @ $18.75", "כניסה שנייה: $55 אם ירד ל-$16.50", "כניסה שלישית: $55 אם ירד ל-$14.80"],
        "entry_now": 18.75, "entry_ideal": 16.67, "entry_patient": 15.10,
        "stop_loss": 14.36, "stop_loss_note": "אם נשבר — צא. לא לנחש.",
        "target_1y": 24.38, "target_3y": 46.88,
        "risk_reward": 1.3, "rr_note": "נמוך מדי",
        "buy_signals": ["מגמה עולה — מעל MA50 וMA200", "MACD חיובי — מומנטום עולה"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "📊 HIMS מופיעה ברשימה בפעם הראשונה — סיגנל ממוקד.",
    },
    {
        "ticker": "NVDA",
        "company_name": "NVIDIA Corporation",
        "sector": "Technology",
        "industry": "Semiconductors",
        "current_price": 118.50,
        "price_52w_high": 153.13,
        "price_52w_low": 86.22,
        "pct_from_52w_high": -22.6,
        "pct_from_ath": -22.6,
        "price_change_1m_pct": 3.1,
        "price_change_3m_pct": -8.5,
        "market_cap": 2_890_000_000_000,
        "revenue_ttm": 130_000_000_000,
        "revenue_growth_yoy": 1.22,
        "gross_margin": 0.745,
        "operating_margin": 0.62,
        "net_margin": 0.558,
        "fcf_ttm": 60_000_000_000,
        "fcf_margin": 0.462,
        "roic": 0.88,
        "roe": 1.18,
        "debt_to_equity": 0.42,
        "current_ratio": 4.2,
        "cash": 43_000_000_000,
        "eps_ttm": 2.94,
        "eps_growth_yoy": 1.45,
        "rd_expense": 8_000_000_000,
        "capex": 2_800_000_000,
        "capex_growth_yoy": 0.22,
        "shares_outstanding": 24_400_000_000,
        "shares_change_yoy": -0.02,
        "short_interest_pct": 0.012,
        "short_ratio": 0.8,
        "pe_ttm": 40.3, "pe_forward": 28.5,
        "ps_ratio": 22.2, "pb_ratio": 47.5,
        "ev_ebitda": 32, "peg_ratio": 0.8,
        "analyst_consensus": "strongBuy",
        "analyst_target_mean": 175.0,
        "analyst_target_high": 220.0,
        "analyst_target_low": 130.0,
        "analyst_count": 42,
        "avg_volume_30d": 250_000_000,
        "today_volume": 310_000_000,
        "accruals_ratio": -0.02,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Wide",
        "moat_sources": ["CUDA ecosystem", "AI infrastructure monopoly", "Data center dominance"],
        "moat_score": 9.5,
        "moat_durability_years": 10,
        "pricing_power": "Strong",
        "fundamental_score": 9.2,
        "growth_score": 9.0,
        "valuation_score": 6.5,
        "valuation_vs_sector": "Fair",
        "dcf_rough_range": "$130-200",
        "multibagger_potential": "High",
        "multibagger_reason_hebrew": "AI הוא המהפכה הגדולה של המאה. NVDA היא תשתית ה-AI. כל דולר שמושקע ב-AI עובר דרכה.",
        "years_to_potential_peak": "3-5 שנים",
        "key_strengths_hebrew": ["CUDA moat בלתי-עביר", "FCF margin 46%", "122% revenue growth"],
        "key_risks_hebrew": ["הערכה גבוהה", "AMD ו-Intel מתחרים", "תלות בסין"],
        "growth_drivers_hebrew": ["Data centers", "Autonomous vehicles", "Robotics"],
        "sector_verdict_hebrew": "יקר ביחס לסקטור אבל מוצדק לחלוטין. Best-in-class.",
        "earnings_quality_comment": "FCF margin 46% — מהטובים בעולם. רווחים אמיתיים.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "AI ממשיך לגדול. NVDA מכפילה revenue תוך 3 שנים.",
        "bear_case_hebrew": "האטה ב-capex של hyperscalers. מחיר גבוה מדי.",
        "psychology_note_hebrew": "זו חברת הליבה של AI. volatility היא נורמלית. החזק.",
        "verdict_hebrew": "⏳ המתן לסאפורט $100-105. אז קנה אגרסיבית.",
        "above_ma50": True, "above_ma200": True,
        "rsi_14": 58.2, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.62,
        "support_1": 112.0, "support_2": 100.5,
        "resistance_1": 130.0, "high_52w": 153.13,
        "volume_ratio": 1.24,
        "technical_score": 7.3,
        "trend": "Bullish",
        "ma20": 115.2, "ma50": 108.4, "ma200": 102.8,
        "basket": "C",
        "aggressive_invest_score": 6.8,
        "intangible_score": 7.5,
        "sentiment_score": 9.0,
        "total_score": 8.4,
        "action": "⏳ המתן לתמיכה",
        "action_color": "amber",
        "explanation": "מניה טובה אבל הטיימינג לא אידיאלי",
        "position_usd": 0,
        "position_note": "לא להיכנס עדיין",
        "dca_plan": [],
        "entry_now": 118.50, "entry_ideal": 113.12, "entry_patient": 102.51,
        "stop_loss": 97.49, "stop_loss_note": "אם נשבר — צא. לא לנחש.",
        "target_1y": 154.05, "target_3y": 296.25,
        "risk_reward": 1.4, "rr_note": "נמוך מדי",
        "buy_signals": ["מגמה עולה — מעל MA50 וMA200", "MACD חיובי — מומנטום עולה"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "💡 זכור: המטרה היא 3-10 שנים. ירידה של 20% בדרך היא נורמלית לחלוטין.",
    },
]

DEMO_WATCHLIST_EXTRA = ["GOOG", "META", "QQQ", "AMD", "PLTR", "QUBT", "XOVR"]

DEMO_PORTFOLIO = {
    "positions": [
        {"ticker": "GOOG",  "price": 182.5,  "score": 7.8, "trend": "Bullish", "pct_from_ath": -11.2, "above_ma200": True,  "rsi_14": 54.2, "action": "✅ המשך להחזיק — חזק"},
        {"ticker": "NVDA",  "price": 118.5,  "score": 8.4, "trend": "Bullish", "pct_from_ath": -22.6, "above_ma200": True,  "rsi_14": 58.2, "action": "✅ המשך להחזיק — חזק"},
        {"ticker": "META",  "price": 642.0,  "score": 8.1, "trend": "Bullish", "pct_from_ath": -5.8,  "above_ma200": True,  "rsi_14": 61.0, "action": "✅ המשך להחזיק — חזק"},
        {"ticker": "QQQ",   "price": 487.0,  "score": 7.2, "trend": "Bullish", "pct_from_ath": -8.1,  "above_ma200": True,  "rsi_14": 55.5, "action": "⏳ החזק — עדיין סביר"},
        {"ticker": "AMD",   "price": 118.0,  "score": 6.9, "trend": "Mixed",   "pct_from_ath": -41.5, "above_ma200": False, "rsi_14": 47.3, "action": "👀 עקוב"},
        {"ticker": "PLTR",  "price": 118.0,  "score": 7.5, "trend": "Bullish", "pct_from_ath": -12.3, "above_ma200": True,  "rsi_14": 62.1, "action": "✅ המשך להחזיק — חזק"},
        {"ticker": "QUBT",  "price": 8.25,   "score": 5.8, "trend": "Bearish", "pct_from_ath": -68.0, "above_ma200": False, "rsi_14": 35.1, "action": "⚠️ שקול לצמצם"},
        {"ticker": "XOVR",  "price": 2.10,   "score": 4.2, "trend": "Bearish", "pct_from_ath": -82.0, "above_ma200": False, "rsi_14": 28.4, "action": "⚠️ שקול לצמצם"},
    ],
    "total_stocks": 8,
}

DEMO_MACRO = {
    "macro": {
        "SPY":      {"name": "S&P 500",     "price": 548.2, "chg_1d": 0.42, "chg_1w": 1.18},
        "QQQ":      {"name": "Nasdaq",      "price": 487.0, "chg_1d": 0.61, "chg_1w": 1.52},
        "^VIX":     {"name": "VIX פחד",     "price": 17.8,  "chg_1d": -3.20, "chg_1w": -8.50},
        "DX-Y.NYB": {"name": "דולר DXY",    "price": 104.2, "chg_1d": 0.05,  "chg_1w": 0.22},
        "TLT":      {"name": "אג\"ח ארוך", "price": 91.4,  "chg_1d": 0.18,  "chg_1w": -0.40},
        "GLD":      {"name": "זהב",         "price": 2305.0,"chg_1d": -0.22, "chg_1w": 0.85},
    },
    "regime": {
        "regime": "NORMAL",
        "hebrew": "שוק רגיל — VIX 17.8",
        "action": "📊 עבוד לפי האלגוריתם הרגיל",
        "color": "blue",
        "weight_adjustment": {},
    }
}
