"""נתוני דמו להדגמת הדוח ללא חיבור לאינטרנט."""

DEMO_STOCKS = [
    {
        "ticker": "LLY",
        "company_name": "Eli Lilly and Company",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "current_price": 780.0,
        "price_52w_high": 972.0,
        "price_52w_low": 680.0,
        "pct_from_52w_high": -19.8,
        "pct_from_ath": -19.8,
        "price_change_1m_pct": 4.5,
        "price_change_3m_pct": -8.2,
        "market_cap": 740_000_000_000,
        "revenue_ttm": 45_000_000_000,
        "revenue_growth_yoy": 0.35,
        "gross_margin": 0.79,
        "operating_margin": 0.35,
        "net_margin": 0.28,
        "fcf_ttm": 12_000_000_000,
        "fcf_margin": 0.267,
        "roic": 0.32,
        "roe": 0.65,
        "debt_to_equity": 1.8,
        "current_ratio": 1.4,
        "cash": 6_500_000_000,
        "eps_ttm": 10.5,
        "eps_growth_yoy": 0.55,
        "rd_expense": 9_000_000_000,
        "capex": 4_200_000_000,
        "capex_growth_yoy": 0.40,
        "shares_outstanding": 950_000_000,
        "shares_change_yoy": -0.01,
        "short_interest_pct": 0.008,
        "short_ratio": 1.2,
        "pe_ttm": 74.3, "pe_forward": 38.0,
        "ps_ratio": 16.5, "pb_ratio": 48.0,
        "ev_ebitda": 42, "peg_ratio": 1.1,
        "analyst_consensus": "strongBuy",
        "analyst_target_mean": 1050.0,
        "analyst_target_high": 1300.0,
        "analyst_target_low": 820.0,
        "analyst_count": 28,
        "avg_volume_30d": 3_200_000,
        "today_volume": 3_800_000,
        "accruals_ratio": -0.01,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Wide",
        "moat_sources": ["GLP-1 near-monopoly (Mounjaro/Zepbound)", "Pipeline depth 100+ drugs", "Manufacturing scale advantage"],
        "moat_score": 9.2,
        "moat_durability_years": 12,
        "pricing_power": "Very Strong",
        "fundamental_score": 8.8,
        "growth_score": 9.2,
        "valuation_score": 7.0,
        "valuation_vs_sector": "Fair",
        "dcf_rough_range": "$900-1400",
        "multibagger_potential": "High",
        "multibagger_reason_hebrew": "תרופות ה-GLP-1 (Mounjaro, Zepbound) הן המהפכה הרפואית הגדולה ביותר של העשור. LLY שולטת בשוק ה-obesity עם נתח 60%+ וצמיחה של 35% YoY.",
        "years_to_potential_peak": "3-5 שנים",
        "key_strengths_hebrew": ["מונופול דה-פקטו על GLP-1", "R&D $9B/שנה — pipeline עמוק", "Gross margin 79% — רוקחות בראשית"],
        "key_risks_hebrew": ["תחרות מ-Novo Nordisk (Ozempic)", "תמחור גבוה — P/E 74", "סיכון רגולטורי FDA/Medicare"],
        "growth_drivers_hebrew": ["Mounjaro — סוכרת ומשקל", "Zepbound — obesity mainstream", "Alzheimer pipeline (donanemab)"],
        "sector_verdict_hebrew": "יקר ביחס לפארמה קלאסית אבל מוצדק — LLY היא חברת צמיחה במסווה פארמה.",
        "earnings_quality_comment": "FCF $12B חיובי חזק, R&D השקעה אמיתית. איכות גבוהה.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "שוק ה-GLP-1 יגיע ל-$130B עד 2030. LLY תכפיל revenue תוך 4 שנים.",
        "bear_case_hebrew": "Novo Nordisk מחזירה נתחי שוק עם Ozempic 2.0. Medicare מגביל תמחור.",
        "psychology_note_hebrew": "ירידה 20% מהשיא — הזדמנות כניסה. הפונדמנטלי לא השתנה.",
        "verdict_hebrew": "✅ קנה בדיפ — זו אחת החברות הטובות בעולם ב-2026.",
        "above_ma50": True, "above_ma200": False,
        "rsi_14": 48.5, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.42,
        "support_1": 740.0, "support_2": 700.0,
        "resistance_1": 820.0, "high_52w": 972.0,
        "volume_ratio": 1.19,
        "technical_score": 7.0,
        "trend": "Mixed",
        "ma20": 768.0, "ma50": 755.0, "ma200": 810.0,
        "basket": "B",
        "aggressive_invest_score": 7.5,
        "intangible_score": 9.0,
        "sentiment_score": 8.5,
        "total_score": 9.0,
        "action": "✅ קנה עכשיו",
        "action_color": "green",
        "explanation": "מנהיגת GLP-1 + pipeline חזק",
        "position_usd": 200,
        "position_note": "$200 — משקל מלא",
        "dca_plan": ["כניסה ראשונה: $70 עכשיו @ $780", "כניסה שנייה: $70 אם ירד ל-$740", "כניסה שלישית: $60 אם ירד ל-$700"],
        "entry_now": 780.0, "entry_ideal": 742.0, "entry_patient": 702.0,
        "stop_loss": 668.0, "stop_loss_note": "מתחת ל-$670 — צא.",
        "target_1y": 950.0, "target_3y": 1300.0,
        "risk_reward": 2.2, "rr_note": "טוב",
        "buy_signals": ["MACD חיובי — מומנטום בנייה", "RSI 48 — לא oversold, לא overbought"],
        "sell_signals": ["מתחת MA200 — זהירות"],
        "wait_signals": [],
        "psychology_note": "💡 LLY ירדה 20% מהשיא — בדיוק שם כדאי לקנות חברות מובילות.",
        "alt_data": {"insider": {"signal": "🟢 Cluster Buy", "buy_count_30d": 4, "cluster_buying": True, "ceo_buying": False, "any_buy": True, "insider_score": 8.0}, "jobs": {"signal": "🟢 מגייסת אגרסיבית", "hiring_signals_found": 6, "job_trend_score": 8.5}, "web_momentum": {"signal": "🟢 מומנטום חיובי", "news_count_7d": 18, "positive_headlines": 14, "negative_headlines": 2, "web_momentum_score": 8.0}, "alt_data_score": 8.2},
        "darvas": {"signal": "📦 בתוך קופסה", "darvas_box_top": 810.0, "darvas_box_bottom": 740.0, "in_box": True, "near_breakout": False, "confirmed_breakout": False, "box_tightness_pct": 9.5, "darvas_score": 6.5},
        "squeeze": {"signal": "⏳ Squeeze מתבנה", "squeeze_active": False, "bw_percentile": 28.0, "breakout_direction": "⏳ Pending", "squeeze_score": 6.0},
        "price_history_30d": [820,815,808,798,790,785,780,775,782,788,795,802,798,790,782,778,774,780,785,790,786,782,779,775,780,784,786,782,780,780.0],
        "news_headlines": ["Eli Lilly's Mounjaro sales surge 85% YoY in Q1 2026", "Zepbound gains approval for cardiovascular indication", "LLY donanemab Alzheimer data shows promise in Phase 3"],
        "dividend_yield": 0.005,
        "buyback_yield": 0.008,
        "capex_pct_revenue": 0.093,
        "rd_pct_revenue": 0.20,
        "what_company_does_hebrew": "Eli Lilly היא חברת תרופות אמריקאית המובילה את מהפכת ה-GLP-1 עם תרופות Mounjaro (סוכרת) ו-Zepbound (השמנה). היא גם מפתחת תרופות לאלצהיימר, סרטן ומחלות אוטו-אימוניות.",
        "moat_explanation_hebrew": "LLY בנתה חפיר רחב דרך ייתרון ה-IP (פטנטים עד 2033) על GLP-1, ושרשרת ייצור ייחודית שקשה מאוד לשכפל. אף מתחרה לא יכול לייצר את Mounjaro בקנה מידה דומה תוך 3 שנים.",
        "short_squeeze_hebrew": "Short interest נמוך (0.8%) — אין פוטנציאל לשורט סקוויז. השוק מאמין בחברה ואין הימור נגדי משמעותי.",
        "insider_activity_hebrew": "4 רכישות פנימיות ב-30 הימים האחרונים — Cluster Buy חיובי. מנהל הפיתוח קנה $2M ממניות ב-$760. סימן אמון בולט.",
        "why_now_hebrew": "יוני 2026 — LLY נסחרת 20% מתחת לשיא לאחר תקופת consolidation. נתוני Zepbound Q1 2026 הראו צמיחה 85% — הרבעון הטוב ביותר בתולדות החברה. הכניסה עכשיו היא לפני אישורי ה-FDA הצפויים ל-Q3 2026.",
        "why_now_english": "June 2026 — LLY trades 20% off peak after consolidation. Zepbound Q1 2026 data showed 85% growth — best quarter in company history. Entry now is ahead of expected FDA approvals in Q3 2026.",
        "geopolitical_impact_hebrew": "מלחמת הסחר ארה\"ב-סין: LLY מייצרת בארה\"ב ובאירופה — כמעט ללא חשיפה לסין. Medicare Negotiation Act: סיכון לתמחור תרופות, אבל Mounjaro הוגן מרגולציה עד 2028. המתח במזרח התיכון: ביקוש לתרופות כרוניות יציב ללא תלות גיאופוליטית.",
        "entry_reasoning_hebrew": "כניסה אידיאלית $740-780 — אזור ה-MA50 ו-Fibonacci 38.2% retracement. Stop loss $668 (מתחת ל-support חזק). Risk/Reward 2.2x — אטרקטיבי לחברה כל-כך חזקה.",
    },
    {
        "ticker": "COST",
        "company_name": "Costco Wholesale Corporation",
        "sector": "Consumer Staples",
        "industry": "Discount Retailers",
        "current_price": 920.0,
        "price_52w_high": 1050.0,
        "price_52w_low": 780.0,
        "pct_from_52w_high": -12.4,
        "pct_from_ath": -12.4,
        "price_change_1m_pct": 2.8,
        "price_change_3m_pct": 5.1,
        "market_cap": 408_000_000_000,
        "revenue_ttm": 248_000_000_000,
        "revenue_growth_yoy": 0.08,
        "gross_margin": 0.129,
        "operating_margin": 0.038,
        "net_margin": 0.026,
        "fcf_ttm": 7_200_000_000,
        "fcf_margin": 0.029,
        "roic": 0.32,
        "roe": 0.38,
        "debt_to_equity": 0.42,
        "current_ratio": 0.96,
        "cash": 14_000_000_000,
        "eps_ttm": 17.8,
        "eps_growth_yoy": 0.12,
        "rd_expense": 0,
        "capex": 4_800_000_000,
        "capex_growth_yoy": 0.10,
        "shares_outstanding": 443_000_000,
        "shares_change_yoy": -0.005,
        "short_interest_pct": 0.006,
        "short_ratio": 1.8,
        "pe_ttm": 51.7, "pe_forward": 45.0,
        "ps_ratio": 1.65, "pb_ratio": 20.0,
        "ev_ebitda": 36, "peg_ratio": 4.3,
        "analyst_consensus": "buy",
        "analyst_target_mean": 1020.0,
        "analyst_target_high": 1200.0,
        "analyst_target_low": 850.0,
        "analyst_count": 32,
        "avg_volume_30d": 1_800_000,
        "today_volume": 2_100_000,
        "accruals_ratio": 0.01,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Wide",
        "moat_sources": ["Membership model — 93% renewal rate", "Bulk pricing power — suppliers can't refuse", "Location/real estate moat"],
        "moat_score": 9.0,
        "moat_durability_years": 20,
        "pricing_power": "Strong",
        "fundamental_score": 8.5,
        "growth_score": 7.5,
        "valuation_score": 6.5,
        "valuation_vs_sector": "Fair",
        "dcf_rough_range": "$900-1200",
        "multibagger_potential": "Medium",
        "multibagger_reason_hebrew": "Costco היא המכונה המושלמת. 93% חידוש membership, expansion בינלאומי, ו-special dividends שגרמו למשקיעים לאהוב אותה עוד יותר.",
        "years_to_potential_peak": "5-8 שנים",
        "key_strengths_hebrew": ["93% membership renewal — נאמנות אגדית", "Recession-proof — אנשים קונים bulk בקשיים", "Special dividends היסטוריים — $15+ למניה"],
        "key_risks_hebrew": ["P/E 51 — יקר לריטייל", "צמיחה 8% — לא מרגשת", "Amazon Fresh מתחרה בחלק"],
        "growth_drivers_hebrew": ["פתיחת חנויות בינלאומיות (ספרד, צ'ילה)", "E-commerce Costco.com", "Membership fee increase הבאה"],
        "sector_verdict_hebrew": "יקר ביחס לריטייל קלאסי — אבל Costco ראויה לפרמיום. המוט הכי חזק בקמעונאות.",
        "earnings_quality_comment": "FCF יציב $7.2B. Membership income = recurring revenue נקי.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "Costco מכפילה membership base בינלאומי. Special dividend $25+ ב-2027.",
        "bear_case_hebrew": "מיתון גלובלי מקטין bulk buying. תחרות Amazon מכרסמת.",
        "psychology_note_hebrew": "Costco ירדה 12% — זו הזדמנות נדירה לקנות את המוט המושלם בדיסקאונט.",
        "verdict_hebrew": "✅ קנה — Costco היא 'sleep well at night' investment. DCA הדרגתי.",
        "above_ma50": True, "above_ma200": True,
        "rsi_14": 55.2, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.58,
        "support_1": 880.0, "support_2": 840.0,
        "resistance_1": 980.0, "high_52w": 1050.0,
        "volume_ratio": 1.17,
        "technical_score": 7.5,
        "trend": "Bullish",
        "ma20": 905.0, "ma50": 888.0, "ma200": 862.0,
        "basket": "B",
        "aggressive_invest_score": 7.0,
        "intangible_score": 8.5,
        "sentiment_score": 8.0,
        "total_score": 8.6,
        "action": "✅ קנה עכשיו",
        "action_color": "green",
        "explanation": "מוט רחב + מחיר הוגן",
        "position_usd": 185,
        "position_note": "$185 — משקל גבוה",
        "dca_plan": ["כניסה ראשונה: $65 עכשיו @ $920", "כניסה שנייה: $65 אם ירד ל-$880", "כניסה שלישית: $55 אם ירד ל-$840"],
        "entry_now": 920.0, "entry_ideal": 888.0, "entry_patient": 845.0,
        "stop_loss": 805.0, "stop_loss_note": "מתחת ל-$805 — צא.",
        "target_1y": 1050.0, "target_3y": 1350.0,
        "risk_reward": 2.5, "rr_note": "טוב",
        "buy_signals": ["מעל MA50 וMA200 — Bullish", "MACD חיובי — מומנטום"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "💡 Costco — הקנייה שאנשים עושים בכל מצב כלכלי. הגנה מושלמת.",
        "alt_data": {"insider": {"signal": "⚪ ניטרלי", "buy_count_30d": 1, "cluster_buying": False, "ceo_buying": False, "any_buy": True, "insider_score": 6.0}, "jobs": {"signal": "🟢 מגייסת", "hiring_signals_found": 5, "job_trend_score": 7.0}, "web_momentum": {"signal": "🟢 חיובי", "news_count_7d": 9, "positive_headlines": 7, "negative_headlines": 1, "web_momentum_score": 7.5}, "alt_data_score": 7.0},
        "darvas": {"signal": "📦 פריצה ממתנת", "darvas_box_top": 960.0, "darvas_box_bottom": 880.0, "in_box": True, "near_breakout": True, "confirmed_breakout": False, "box_tightness_pct": 8.7, "darvas_score": 7.0},
        "squeeze": {"signal": "⏳ Squeeze ניטרלי", "squeeze_active": False, "bw_percentile": 40.0, "breakout_direction": "⏳ Pending", "squeeze_score": 6.5},
        "price_history_30d": [895,900,908,915,920,916,912,908,912,916,920,918,914,910,914,918,922,920,916,912,916,920,924,922,918,920,922,920,918,920.0],
        "news_headlines": ["Costco reports record membership fee revenue in Q2 2026", "Costco expands to 3 new international markets in 2026", "Analyst upgrades COST to Strong Buy ahead of fee increase"],
        "dividend_yield": 0.005,
        "buyback_yield": 0.003,
        "capex_pct_revenue": 0.019,
        "rd_pct_revenue": 0.0,
        "why_now_hebrew": "יוני 2026 — Costco נסחרת 12% מהשיא לאחר sell-off כללי בשוק. העלאת דמי membership צפויה ב-Q4 2026 — קטליסט ברור. Special dividend הבא צפוי ב-2027 ($20+). זו נקודת כניסה נדירה.",
        "why_now_english": "June 2026 — Costco trades 12% off peak following broad market sell-off. Membership fee increase expected Q4 2026 — clear catalyst. Next special dividend expected 2027 ($20+). Rare entry opportunity.",
        "geopolitical_impact_hebrew": "מלחמת הסחר: Costco מגדרת עצמה עם suppliers אמריקאים ומקסיקניים. מיתון פוטנציאלי: דווקא חיובי — אנשים עוברים ל-bulk buying בלחץ כלכלי. שיעורי ריבית: ירידה צפויה של הפד תיטיב עם מניות consumer staples.",
        "entry_reasoning_hebrew": "כניסה $880-920 — אזור ה-MA200 ו-support היסטורי. P/E Forward 45x הוגן ל-Costco. Stop $805 = מתחת ל-52w low support. Target $1350 ב-3 שנים = CAGR 14%.",
    },
    {
        "ticker": "MSFT",
        "company_name": "Microsoft Corporation",
        "sector": "Technology",
        "industry": "Cloud Computing / Software",
        "current_price": 420.0,
        "price_52w_high": 468.0,
        "price_52w_low": 360.0,
        "pct_from_52w_high": -10.3,
        "pct_from_ath": -10.3,
        "price_change_1m_pct": 3.2,
        "price_change_3m_pct": 6.8,
        "market_cap": 3_120_000_000_000,
        "revenue_ttm": 245_000_000_000,
        "revenue_growth_yoy": 0.17,
        "gross_margin": 0.695,
        "operating_margin": 0.44,
        "net_margin": 0.36,
        "fcf_ttm": 74_000_000_000,
        "fcf_margin": 0.302,
        "roic": 0.32,
        "roe": 0.42,
        "debt_to_equity": 0.35,
        "current_ratio": 1.8,
        "cash": 80_000_000_000,
        "eps_ttm": 13.10,
        "eps_growth_yoy": 0.20,
        "rd_expense": 28_000_000_000,
        "capex": 44_000_000_000,
        "capex_growth_yoy": 0.55,
        "shares_outstanding": 7_430_000_000,
        "shares_change_yoy": -0.01,
        "short_interest_pct": 0.005,
        "short_ratio": 1.5,
        "pe_ttm": 32.1, "pe_forward": 28.0,
        "ps_ratio": 12.7, "pb_ratio": 13.5,
        "ev_ebitda": 22, "peg_ratio": 1.4,
        "analyst_consensus": "strongBuy",
        "analyst_target_mean": 520.0,
        "analyst_target_high": 600.0,
        "analyst_target_low": 420.0,
        "analyst_count": 50,
        "avg_volume_30d": 22_000_000,
        "today_volume": 25_000_000,
        "accruals_ratio": -0.01,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Wide",
        "moat_sources": ["Azure ecosystem lock-in", "Office 365 subscription moat", "LinkedIn data network"],
        "moat_score": 9.3,
        "moat_durability_years": 15,
        "pricing_power": "Very Strong",
        "fundamental_score": 9.0,
        "growth_score": 8.5,
        "valuation_score": 8.0,
        "valuation_vs_sector": "Fair",
        "dcf_rough_range": "$460-600",
        "multibagger_potential": "Medium",
        "multibagger_reason_hebrew": "Microsoft + OpenAI = שליטה על AI enterprise. Azure גדל 28% YoY. כל עסק בעולם ישלם Microsoft עבור AI. זו השקעה בתשתית דיגיטלית של העולם.",
        "years_to_potential_peak": "3-5 שנים",
        "key_strengths_hebrew": ["Azure growth 28% YoY", "FCF $74B — מדהים", "Copilot AI integration בכל מוצר"],
        "key_risks_hebrew": ["Capex עולה $44B — AI infrastructure", "AWS ו-Google Cloud מתחרים", "תמחור premium"],
        "growth_drivers_hebrew": ["Azure AI services", "GitHub Copilot", "Office 365 Copilot enterprise"],
        "sector_verdict_hebrew": "P/E 28 Forward — הוגן מאוד לחברה עם MOAT כזה. זול ביחס לנאסדאק.",
        "earnings_quality_comment": "FCF $74B — אחד הגבוהים בעולם. רווחים אמיתיים.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "Azure מגיע ל-$200B revenue ב-2028. Copilot B2B מניע pricing power חדש.",
        "bear_case_hebrew": "AWS שומרת את המנהיגות. AI capex לא מחזיר ROI.",
        "psychology_note_hebrew": "MSFT — ה'boring winner'. לא מרגשת, אבל תמיד מכה.",
        "verdict_hebrew": "✅ קנה — אחת ה-10 מניות הטובות בעולם ב-2026.",
        "above_ma50": True, "above_ma200": True,
        "rsi_14": 57.8, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.60,
        "support_1": 400.0, "support_2": 375.0,
        "resistance_1": 450.0, "high_52w": 468.0,
        "volume_ratio": 1.14,
        "technical_score": 7.8,
        "trend": "Bullish",
        "ma20": 412.0, "ma50": 405.0, "ma200": 392.0,
        "basket": "B",
        "aggressive_invest_score": 7.5,
        "intangible_score": 9.0,
        "sentiment_score": 8.5,
        "total_score": 8.8,
        "action": "✅ קנה עכשיו",
        "action_color": "green",
        "explanation": "Azure + AI + dividend + buybacks",
        "position_usd": 210,
        "position_note": "$210 — משקל מלא",
        "dca_plan": ["כניסה ראשונה: $70 עכשיו @ $420", "כניסה שנייה: $70 אם ירד ל-$400", "כניסה שלישית: $70 אם ירד ל-$375"],
        "entry_now": 420.0, "entry_ideal": 400.0, "entry_patient": 376.0,
        "stop_loss": 358.0, "stop_loss_note": "מתחת ל-52w low — צא.",
        "target_1y": 500.0, "target_3y": 680.0,
        "risk_reward": 2.1, "rr_note": "טוב",
        "buy_signals": ["מעל MA50 וMA200 — Bullish ברור", "MACD חיובי"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "💡 MSFT — 30 שנה של beat estimates. אל תלחם בחברה הזו.",
        "alt_data": {"insider": {"signal": "⚪ ניטרלי", "buy_count_30d": 2, "cluster_buying": False, "ceo_buying": False, "any_buy": True, "insider_score": 6.5}, "jobs": {"signal": "🟢 מגייסת AI בכבדות", "hiring_signals_found": 8, "job_trend_score": 9.0}, "web_momentum": {"signal": "🟢 חיובי מאוד", "news_count_7d": 22, "positive_headlines": 18, "negative_headlines": 2, "web_momentum_score": 8.5}, "alt_data_score": 8.0},
        "darvas": {"signal": "📦 Consolidation", "darvas_box_top": 445.0, "darvas_box_bottom": 400.0, "in_box": True, "near_breakout": True, "confirmed_breakout": False, "box_tightness_pct": 10.0, "darvas_score": 7.0},
        "squeeze": {"signal": "⏳ Squeeze ניטרלי", "squeeze_active": False, "bw_percentile": 35.0, "breakout_direction": "⏳ Pending", "squeeze_score": 6.5},
        "price_history_30d": [408,410,412,415,418,420,416,414,412,415,418,422,420,418,415,418,420,422,420,418,420,422,424,422,420,420,418,420,422,420.0],
        "news_headlines": ["Microsoft Azure revenue grows 28% in Q1 2026", "GitHub Copilot reaches 2 million enterprise users", "Microsoft announces $10B additional buyback program"],
        "dividend_yield": 0.008,
        "buyback_yield": 0.018,
        "capex_pct_revenue": 0.18,
        "rd_pct_revenue": 0.114,
        "why_now_hebrew": "יוני 2026 — MSFT נסחרת 10% מהשיא לאחר sell-off AI stocks. Azure Q2 2026 beat estimates. הכניסה עכשיו היא לפני earnings Q3 הצפויים לאוגוסט — Copilot enterprise adoption מאיצה.",
        "why_now_english": "June 2026 — MSFT trades 10% off peak after AI sector sell-off. Azure Q2 2026 beat estimates. Entry now is ahead of Q3 earnings expected in August — Copilot enterprise adoption accelerating.",
        "geopolitical_impact_hebrew": "מלחמת הסחר ארה\"ב-סין: Microsoft הוציאה מסין — חשיפה מינימלית. NATO רחימה: ממשלות אירופיות רוכשות Azure Government. ריבית יורדת: חיובי לענקיות טכנולוגיה. AI Arms Race: Microsoft/OpenAI בחזית — מרוויחה מכל כיוון.",
        "entry_reasoning_hebrew": "כניסה $400-420 — MA50 support. P/E Forward 28x = הוגן לחברה עם 17% growth. Stop $358 = מתחת ל-52w low. Target $680 ב-3 שנים = CAGR 17%.",
    },
    {
        "ticker": "NVDA",
        "company_name": "IonQ, Inc.",
        "sector": "Technology",
        "industry": "Quantum Computing",
        "current_price": 12.45,
        "price_52w_high": 48.50,
        "price_52w_low": 8.20,
        "pct_from_52w_high": -74.3,
        "pct_from_ath": -74.3,
        "price_change_1m_pct": -8.2,
        "price_change_3m_pct": -22.1,
        "market_cap": 2_100_000_000,
        "revenue_ttm": 36_000_000,
        "revenue_growth_yoy": 0.98,
        "gross_margin": 0.49,
        "operating_margin": -2.80,
        "net_margin": -2.60,
        "fcf_ttm": -85_000_000,
        "fcf_margin": -0.36,
        "roic": -0.18,
        "roe": -0.45,
        "debt_to_equity": 0.25,
        "current_ratio": 4.2,
        "cash": 350_000_000,
        "eps_ttm": -1.20,
        "eps_growth_yoy": 0.30,
        "rd_expense": 60_000_000,
        "capex": 12_000_000,
        "capex_growth_yoy": 0.45,
        "shares_outstanding": 168_000_000,
        "shares_change_yoy": 0.08,
        "short_interest_pct": 0.18,
        "short_ratio": 3.2,
        "pe_ttm": 0, "pe_forward": 0,
        "ps_ratio": 58.0, "pb_ratio": 3.2,
        "ev_ebitda": 0, "peg_ratio": 0,
        "analyst_consensus": "buy",
        "analyst_target_mean": 22.0,
        "analyst_target_high": 40.0,
        "analyst_target_low": 10.0,
        "analyst_count": 8,
        "avg_volume_30d": 4_500_000,
        "today_volume": 6_200_000,
        "accruals_ratio": 0.05,
        "earnings_quality": "Medium",
        "earnings_flags": ["⚠️ דילול מניות משמעותי"],
        "quality_score_bonus": -0.3,
        "moat_type": "Narrow",
        "moat_sources": ["פטנטים בטכנולוגיית קוונטום", "קשרים עם IBM ו-Amazon"],
        "moat_score": 6.5,
        "moat_durability_years": 7,
        "pricing_power": "Moderate",
        "fundamental_score": 5.0,
        "growth_score": 8.5,
        "valuation_score": 5.5,
        "valuation_vs_sector": "Fair",
        "dcf_rough_range": "$8-25",
        "multibagger_potential": "Very High",
        "multibagger_reason_hebrew": "קוונטום קומפיוטינג היא שוק של טריליון דולר. IonQ עם הטכנולוגיה המובילה ותחת $2B market cap — זו ההזדמנות לפני שהשוק מבין.",
        "years_to_potential_peak": "4-7 שנים",
        "key_strengths_hebrew": ["מובילה בדיוק קוונטום", "שותפויות עם ענקיות הטק", "מאגר מזומנים לשנים"],
        "key_risks_hebrew": ["עדיין לא רווחית", "תחרות מ-IBM, Google", "טכנולוגיה לא בשלה"],
        "growth_drivers_hebrew": ["ענן קוונטום", "ביטחון לאומי", "תרופות ולוגיסטיקה"],
        "sector_verdict_hebrew": "זולה ביחס לפוטנציאל הענפי. רוב המתחרים גדולים פי 10+.",
        "earnings_quality_comment": "שורף מזומנים — נורמלי לשלב זה. אבל 18% short interest מסוכן.",
        "short_squeeze_potential": True,
        "bull_case_hebrew": "קוונטום מגיע בשנות ה-30. IonQ תהיה ה-NVIDIA של הקוונטום.",
        "bear_case_hebrew": "IBM ו-Google מוחקים אותה. מזומנים נגמרים לפני שהמוצר בשל.",
        "psychology_note_hebrew": "ירידה של 74% מהשיא — זה המשחק. אם התזה נכונה, האסימטריה מנצחת.",
        "verdict_hebrew": "⭐ TOP PICK — כניסה ב-DCA. קנה שליש עכשיו, שליש ב-$10, שליש ב-$8.",
        "above_ma50": False, "above_ma200": False,
        "rsi_14": 38.5, "rsi_signal": "Oversold",
        "macd_bullish": False, "bb_pct": 0.12,
        "support_1": 10.80, "support_2": 9.50,
        "resistance_1": 15.20, "high_52w": 48.50,
        "volume_ratio": 1.38,
        "technical_score": 6.2,
        "trend": "Bearish",
        "ma20": 13.1, "ma50": 16.8, "ma200": 24.5,
        "basket": "A",
        "aggressive_invest_score": 7.0,
        "intangible_score": 8.0,
        "sentiment_score": 6.5,
        "total_score": 7.2,
        "action": "✅ צבור הדרגתית",
        "action_color": "green",
        "explanation": "Oversold + פוטנציאל Very High",
        "position_usd": 110,
        "position_note": "$110 — כניסה ראשונית בלבד (10%)",
        "dca_plan": ["כניסה ראשונה: $37 עכשיו @ $12.45", "כניסה שנייה: $37 אם ירד ל-$10.80", "כניסה שלישית: $37 אם ירד ל-$9.50"],
        "entry_now": 12.45, "entry_ideal": 10.91, "entry_patient": 9.69,
        "stop_loss": 9.22, "stop_loss_note": "אם נשבר — צא. לא לנחש.",
        "target_1y": 16.19, "target_3y": 31.13,
        "risk_reward": 0.9, "rr_note": "נמוך מדי",
        "buy_signals": ["RSI 38 — oversold, הזדמנות", "ליד Bollinger התחתון — לחץ מכירה מוגזם"],
        "sell_signals": ["מתחת MA200 — מגמה יורדת"],
        "wait_signals": [],
        "psychology_note": "⚠️ IONQ ירדה 74% מהשיא. זה לא סיבה למכור — זו הסיבה שבדקנו אותה. בדוק: האם התזה המקורית עדיין תקפה?",
        "alt_data": {"insider": {"signal": "🟢 Cluster Buy", "buy_count_30d": 3, "cluster_buying": True, "ceo_buying": True, "any_buy": True, "insider_score": 8.5}, "jobs": {"signal": "🟢 מגייסת אגרסיבית", "hiring_signals_found": 4, "job_trend_score": 7.0}, "web_momentum": {"signal": "🟢 מומנטום חיובי", "news_count_7d": 12, "positive_headlines": 8, "negative_headlines": 2, "web_momentum_score": 7.5}, "alt_data_score": 7.8},
        "darvas": {"signal": "⚡ קרוב לפריצה", "darvas_box_top": 14.20, "darvas_box_bottom": 11.50, "in_box": True, "near_breakout": True, "confirmed_breakout": False, "box_tightness_pct": 4.2, "darvas_score": 7.5},
        "squeeze": {"signal": "🔥 Squeeze פעיל! 🟢 Up", "squeeze_active": True, "bw_percentile": 12.0, "breakout_direction": "🟢 Up", "squeeze_score": 8.0},
        "price_history_30d": [12.1,11.8,11.5,11.9,12.3,12.0,11.7,11.4,11.6,12.0,12.2,12.5,12.3,12.1,11.9,12.2,12.4,12.1,11.8,12.0,12.3,12.5,12.4,12.2,12.0,12.3,12.5,12.4,12.3,12.45],
        "news_headlines": ["IonQ Reports Record Revenue Growth in Q3", "Quantum computing stocks surge on new government contract", "IonQ expands partnership with major cloud provider"],
        "dividend_yield": 0.0,
        "buyback_yield": 0.0,
        "capex_pct_revenue": 0.333,
        "rd_pct_revenue": 1.667,
        "why_now_hebrew": "יוני 2026 — IonQ ירדה 74% מהשיא. RSI 38 = oversold. חוזה ממשלתי חדש צפוי Q3 2026. מזומן $350M מספיק ל-3+ שנים. זו הכניסה הספקולטיבית לפני breakout.",
        "why_now_english": "June 2026 — IonQ down 74% from peak. RSI 38 = oversold. New government contract expected Q3 2026. $350M cash covers 3+ years. This is the speculative entry before breakout.",
        "geopolitical_impact_hebrew": "מרוץ קוונטום ארה\"ב-סין: ממשל ביידן/האריס הגדיל מימון קוונטום ל-$3B. IonQ מרוויחה. ביטחון לאומי: NSA ו-DoD בוחנים קריפטוגרפיה קוונטומית — IonQ שם. ריבית גבוהה: לחץ על מניות גדילה ללא רווח.",
        "entry_reasoning_hebrew": "כניסה $10-12 — DCA בשלישים. Stop $9.22 = מתחת ל-support. Target $16 ב-1 שנה = 33% upside. R/R נמוך אבל הפוטנציאל ה-3-5 שנתי הוא x5-10.",
    },
    {
        "ticker": "HIMS",
        "company_name": "Hims & Hers Health, Inc.",
        "sector": "Healthcare",
        "industry": "Telehealth",
        "current_price": 18.75,
        "price_52w_high": 72.0,
        "price_52w_low": 14.20,
        "pct_from_52w_high": -74.0,
        "pct_from_ath": -74.0,
        "price_change_1m_pct": 5.2,
        "price_change_3m_pct": -31.0,
        "market_cap": 3_800_000_000,
        "revenue_ttm": 870_000_000,
        "revenue_growth_yoy": 0.67,
        "gross_margin": 0.79,
        "operating_margin": 0.05,
        "net_margin": 0.04,
        "fcf_ttm": 40_000_000,
        "fcf_margin": 0.046,
        "roic": 0.08,
        "roe": 0.12,
        "debt_to_equity": 0.18,
        "current_ratio": 2.8,
        "cash": 200_000_000,
        "eps_ttm": 0.12,
        "eps_growth_yoy": 2.5,
        "rd_expense": 30_000_000,
        "capex": 50_000_000,
        "capex_growth_yoy": 0.35,
        "shares_outstanding": 202_000_000,
        "shares_change_yoy": 0.03,
        "short_interest_pct": 0.22,
        "short_ratio": 4.1,
        "pe_ttm": 156, "pe_forward": 28,
        "ps_ratio": 4.4, "pb_ratio": 6.5,
        "ev_ebitda": 48, "peg_ratio": 0.8,
        "analyst_consensus": "buy",
        "analyst_target_mean": 35.0,
        "analyst_target_high": 55.0,
        "analyst_target_low": 15.0,
        "analyst_count": 12,
        "avg_volume_30d": 8_000_000,
        "today_volume": 11_000_000,
        "accruals_ratio": 0.02,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Narrow",
        "moat_sources": ["מותג חזק", "מנויים חוזרים", "פלטפורמת תרופות מותאמות"],
        "moat_score": 6.8,
        "moat_durability_years": 5,
        "pricing_power": "Strong",
        "fundamental_score": 7.2,
        "growth_score": 8.8,
        "valuation_score": 7.0,
        "valuation_vs_sector": "Undervalued",
        "dcf_rough_range": "$25-50",
        "multibagger_potential": "High",
        "multibagger_reason_hebrew": "טלהלט + תרופות מותאמות = שוק $100B. HIMS בדרך לכבוש אותו עם FCF חיובי ו-79% gross margin.",
        "years_to_potential_peak": "3-5 שנים",
        "key_strengths_hebrew": ["Gross margin 79% — נדיר בביוטק", "FCF חיובי בשנה 5", "צמיחה 67% YoY"],
        "key_risks_hebrew": ["תחרות מ-Roman, Teladoc", "רגולציה FDA על תרופות GLP-1", "Short interest 22%"],
        "growth_drivers_hebrew": ["תרופות לירידה במשקל (GLP-1)", "הרחבה לנשים", "פלטפורמת mental health"],
        "sector_verdict_hebrew": "זול ביחס לביוטק. P/S 4.4 עם 67% צמיחה = ממש אטרקטיבי.",
        "earnings_quality_comment": "FCF חיובי + gross margin 79% = איכות גבוהה מאוד.",
        "short_squeeze_potential": True,
        "bull_case_hebrew": "HIMS הופכת ל-Walmart של תרופות דיגיטליות. $5B revenue ב-2028.",
        "bear_case_hebrew": "FDA מגביל GLP-1 compounding. התחרות מ-Novo Nordisk מוחצת.",
        "psychology_note_hebrew": "74% מהשיא — בדיוק שם נוצרים multibaggers. הפונדמנטלי השתפר, המחיר ירד.",
        "verdict_hebrew": "✅ קנה עכשיו — FCF חיובי, צמיחה אדירה, מחיר אטרקטיבי.",
        "above_ma50": True, "above_ma200": False,
        "rsi_14": 52.3, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.55,
        "support_1": 16.50, "support_2": 14.80,
        "resistance_1": 22.0, "high_52w": 72.0,
        "volume_ratio": 1.37,
        "technical_score": 6.8,
        "trend": "Mixed",
        "ma20": 17.8, "ma50": 17.2, "ma200": 28.4,
        "basket": "A",
        "aggressive_invest_score": 6.5,
        "intangible_score": 6.0,
        "sentiment_score": 7.0,
        "total_score": 7.6,
        "action": "✅ קנה עכשיו",
        "action_color": "green",
        "explanation": "סיגנלים חיוביים + פונדמנטלי חזק",
        "position_usd": 165,
        "position_note": "$165 — כניסה בינונית (15%)",
        "dca_plan": ["כניסה ראשונה: $55 עכשיו @ $18.75", "כניסה שנייה: $55 אם ירד ל-$16.50", "כניסה שלישית: $55 אם ירד ל-$14.80"],
        "entry_now": 18.75, "entry_ideal": 16.67, "entry_patient": 15.10,
        "stop_loss": 14.36, "stop_loss_note": "אם נשבר — צא. לא לנחש.",
        "target_1y": 24.38, "target_3y": 46.88,
        "risk_reward": 1.3, "rr_note": "נמוך מדי",
        "buy_signals": ["מגמה עולה — מעל MA50 וMA200", "MACD חיובי — מומנטום עולה"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "📊 HIMS מופיעה ברשימה בפעם הראשונה — סיגנל ממוקד.",
        "dividend_yield": 0.0,
        "buyback_yield": 0.0,
        "capex_pct_revenue": 0.057,
        "rd_pct_revenue": 0.034,
        "why_now_hebrew": "יוני 2026 — HIMS ירדה 74% מהשיא, RSI מעל 50 — momentum חיובי. FDA אישרה compound GLP-1 עד סוף 2025. Q1 2026 FCF חיובי לראשונה — מפנה אסטרטגי.",
        "why_now_english": "June 2026 — HIMS down 74% from peak, RSI above 50 — positive momentum. FDA approved compound GLP-1 through end 2025. Q1 2026 first FCF positive — strategic inflection point.",
        "geopolitical_impact_hebrew": "FDA רגולציה: הסיכון הגדול — כל החלטה על GLP-1 compounding זזה ב-10%+. Medicare: HIMS לא תלויה ב-Medicare (B2C direct). תחרות גיאופוליטית: Novo Nordisk דנית — HIMS אמריקאית טהורה.",
        "entry_reasoning_hebrew": "כניסה $16-19 — DCA. Stop $14.36 = support חזק. Target $35 (analyst mean). R/R 1.3x — נמוך, אבל short squeeze פוטנציאל ב-22% short interest.",
    },
    {
        "ticker": "NVDA",
        "company_name": "NVIDIA Corporation",
        "sector": "Technology",
        "industry": "Semiconductors",
        "current_price": 118.50,
        "price_52w_high": 153.13,
        "price_52w_low": 86.22,
        "pct_from_52w_high": -22.6,
        "pct_from_ath": -22.6,
        "price_change_1m_pct": 3.1,
        "price_change_3m_pct": -8.5,
        "market_cap": 2_890_000_000_000,
        "revenue_ttm": 130_000_000_000,
        "revenue_growth_yoy": 1.22,
        "gross_margin": 0.745,
        "operating_margin": 0.62,
        "net_margin": 0.558,
        "fcf_ttm": 60_000_000_000,
        "fcf_margin": 0.462,
        "roic": 0.88,
        "roe": 1.18,
        "debt_to_equity": 0.42,
        "current_ratio": 4.2,
        "cash": 43_000_000_000,
        "eps_ttm": 2.94,
        "eps_growth_yoy": 1.45,
        "rd_expense": 8_000_000_000,
        "capex": 2_800_000_000,
        "capex_growth_yoy": 0.22,
        "shares_outstanding": 24_400_000_000,
        "shares_change_yoy": -0.02,
        "short_interest_pct": 0.012,
        "short_ratio": 0.8,
        "pe_ttm": 40.3, "pe_forward": 28.5,
        "ps_ratio": 22.2, "pb_ratio": 47.5,
        "ev_ebitda": 32, "peg_ratio": 0.8,
        "analyst_consensus": "strongBuy",
        "analyst_target_mean": 175.0,
        "analyst_target_high": 220.0,
        "analyst_target_low": 130.0,
        "analyst_count": 42,
        "avg_volume_30d": 250_000_000,
        "today_volume": 310_000_000,
        "accruals_ratio": -0.02,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Wide",
        "moat_sources": ["CUDA ecosystem", "AI infrastructure monopoly", "Data center dominance"],
        "moat_score": 9.5,
        "moat_durability_years": 10,
        "pricing_power": "Strong",
        "fundamental_score": 9.2,
        "growth_score": 9.0,
        "valuation_score": 6.5,
        "valuation_vs_sector": "Fair",
        "dcf_rough_range": "$130-200",
        "multibagger_potential": "High",
        "multibagger_reason_hebrew": "AI הוא המהפכה הגדולה של המאה. NVDA היא תשתית ה-AI. כל דולר שמושקע ב-AI עובר דרכה.",
        "years_to_potential_peak": "3-5 שנים",
        "key_strengths_hebrew": ["CUDA moat בלתי-עביר", "FCF margin 46%", "122% revenue growth"],
        "key_risks_hebrew": ["הערכה גבוהה", "AMD ו-Intel מתחרים", "תלות בסין"],
        "growth_drivers_hebrew": ["Data centers", "Autonomous vehicles", "Robotics"],
        "sector_verdict_hebrew": "יקר ביחס לסקטור אבל מוצדק לחלוטין. Best-in-class.",
        "earnings_quality_comment": "FCF margin 46% — מהטובים בעולם. רווחים אמיתיים.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "AI ממשיך לגדול. NVDA מכפילה revenue תוך 3 שנים.",
        "bear_case_hebrew": "האטה ב-capex של hyperscalers. מחיר גבוה מדי.",
        "psychology_note_hebrew": "זו חברת הליבה של AI. volatility היא נורמלית. החזק.",
        "verdict_hebrew": "⏳ המתן לסאפורט $100-105. אז קנה אגרסיבית.",
        "above_ma50": True, "above_ma200": True,
        "rsi_14": 58.2, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.62,
        "support_1": 112.0, "support_2": 100.5,
        "resistance_1": 130.0, "high_52w": 153.13,
        "volume_ratio": 1.24,
        "technical_score": 7.3,
        "trend": "Bullish",
        "ma20": 115.2, "ma50": 108.4, "ma200": 102.8,
        "basket": "C",
        "aggressive_invest_score": 6.8,
        "intangible_score": 7.5,
        "sentiment_score": 9.0,
        "total_score": 8.4,
        "action": "⏳ המתן לתמיכה",
        "action_color": "amber",
        "explanation": "מניה טובה אבל הטיימינג לא אידיאלי",
        "position_usd": 0,
        "position_note": "לא להיכנס עדיין",
        "dca_plan": [],
        "entry_now": 118.50, "entry_ideal": 113.12, "entry_patient": 102.51,
        "stop_loss": 97.49, "stop_loss_note": "אם נשבר — צא. לא לנחש.",
        "target_1y": 154.05, "target_3y": 296.25,
        "risk_reward": 1.4, "rr_note": "נמוך מדי",
        "buy_signals": ["מגמה עולה — מעל MA50 וMA200", "MACD חיובי — מומנטום עולה"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "💡 זכור: המטרה היא 3-10 שנים. ירידה של 20% בדרך היא נורמלית לחלוטין.",
        "dividend_yield": 0.0,
        "buyback_yield": 0.015,
        "capex_pct_revenue": 0.022,
        "rd_pct_revenue": 0.062,
        "why_now_hebrew": "יוני 2026 — NVDA ירדה 22% מהשיא. Blackwell GPU shipments מאיצות. Data center capex hyperscalers לא נעצר. כניסה לפני Q2 earnings אוגוסט 2026.",
        "why_now_english": "June 2026 — NVDA down 22% from peak. Blackwell GPU shipments accelerating. Hyperscaler data center capex unabated. Entry ahead of Q2 earnings August 2026.",
        "geopolitical_impact_hebrew": "מלחמת הסחר ארה\"ב-סין: הגבלות יצוא GPU לסין ($15B revenue בסיכון). NVDA מפצה עם H20 מוגבל. ביטחון לאומי: DoD בונה AI supercomputers — NVDA ספקית בלעדית. AI Arms Race: כל מדינה מגדילה GPU reserves.",
        "entry_reasoning_hebrew": "כניסה $100-118 — אזור MA200. P/E Forward 28.5x = הוגן ל-122% revenue growth. Stop $97 = מתחת ל-52w low support. Target $296 ב-3 שנים = CAGR 36%.",
    },
    {
        "ticker": "AMZN",
        "company_name": "Amazon.com, Inc.",
        "sector": "Consumer Discretionary",
        "industry": "E-Commerce / Cloud",
        "current_price": 210.0,
        "price_52w_high": 242.0,
        "price_52w_low": 168.0,
        "pct_from_52w_high": -13.2,
        "pct_from_ath": -13.2,
        "price_change_1m_pct": 5.5,
        "price_change_3m_pct": 8.2,
        "market_cap": 2_220_000_000_000,
        "revenue_ttm": 638_000_000_000,
        "revenue_growth_yoy": 0.12,
        "gross_margin": 0.485,
        "operating_margin": 0.105,
        "net_margin": 0.075,
        "fcf_ttm": 38_000_000_000,
        "fcf_margin": 0.060,
        "roic": 0.18,
        "roe": 0.28,
        "debt_to_equity": 0.65,
        "current_ratio": 1.1,
        "cash": 88_000_000_000,
        "eps_ttm": 4.20,
        "eps_growth_yoy": 0.65,
        "rd_expense": 85_000_000_000,
        "capex": 78_000_000_000,
        "capex_growth_yoy": 0.50,
        "shares_outstanding": 10_560_000_000,
        "shares_change_yoy": -0.005,
        "short_interest_pct": 0.007,
        "short_ratio": 1.4,
        "pe_ttm": 50.0, "pe_forward": 32.0,
        "ps_ratio": 3.48, "pb_ratio": 8.5,
        "ev_ebitda": 24, "peg_ratio": 1.2,
        "analyst_consensus": "strongBuy",
        "analyst_target_mean": 270.0,
        "analyst_target_high": 320.0,
        "analyst_target_low": 210.0,
        "analyst_count": 55,
        "avg_volume_30d": 45_000_000,
        "today_volume": 52_000_000,
        "accruals_ratio": 0.02,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Wide",
        "moat_sources": ["AWS cloud infrastructure lock-in", "Prime membership flywheel", "Logistics network monopoly"],
        "moat_score": 9.0,
        "moat_durability_years": 12,
        "pricing_power": "Strong",
        "fundamental_score": 8.2,
        "growth_score": 8.8,
        "valuation_score": 8.5,
        "valuation_vs_sector": "Undervalued",
        "dcf_rough_range": "$220-350",
        "multibagger_potential": "High",
        "multibagger_reason_hebrew": "Amazon = AWS + Retail + Ads + AI. AWS לבד שווה $1.5T לפי הערכות. כשה-retail מפסיק להיות הסיפור הראשי, ה-margins יתפוצצו.",
        "years_to_potential_peak": "3-5 שנים",
        "key_strengths_hebrew": ["AWS 29% margin — מנוע הרווח", "Advertising $56B — growing 30%+", "AI/Bedrock infrastructure"],
        "key_risks_hebrew": ["Capex $78B — ריסוק FCF", "Azure ו-GCP מציגים תחרות", "Antitrust risk אמריקאי"],
        "growth_drivers_hebrew": ["AWS AI services", "Prime Video ads", "Kuiper satellite internet"],
        "sector_verdict_hebrew": "זול ביחס ל-tech. P/E Forward 32 עם 12% revenue growth + AWS margin expansion.",
        "earnings_quality_comment": "FCF $38B שלילי ל-capex high. Operating margin 10.5% — בנייה לעתיד.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "AWS margins מגיעים ל-40%. Amazon הופכת לחברה הרווחית ביותר בעולם.",
        "bear_case_hebrew": "Capex AI לא מחזיר ROI. Retail margins נשארים דחוסים.",
        "psychology_note_hebrew": "Amazon — המניה שכולם 'יודעים שצריך לקנות' אבל לא קונים. זה הזמן.",
        "verdict_hebrew": "✅ קנה — AWS + AI + Ads = מכונת רווח לעשור הבא.",
        "above_ma50": True, "above_ma200": True,
        "rsi_14": 58.5, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.62,
        "support_1": 195.0, "support_2": 178.0,
        "resistance_1": 225.0, "high_52w": 242.0,
        "volume_ratio": 1.16,
        "technical_score": 7.5,
        "trend": "Bullish",
        "ma20": 205.0, "ma50": 198.0, "ma200": 188.0,
        "basket": "B",
        "aggressive_invest_score": 7.2,
        "intangible_score": 8.5,
        "sentiment_score": 8.0,
        "total_score": 8.5,
        "action": "✅ קנה עכשיו",
        "action_color": "green",
        "explanation": "AWS expansion + margin improvement",
        "position_usd": 195,
        "position_note": "$195 — משקל גבוה",
        "dca_plan": ["כניסה ראשונה: $65 עכשיו @ $210", "כניסה שנייה: $65 אם ירד ל-$195", "כניסה שלישית: $65 אם ירד ל-$178"],
        "entry_now": 210.0, "entry_ideal": 195.0, "entry_patient": 179.0,
        "stop_loss": 169.0, "stop_loss_note": "מתחת ל-$169 — צא.",
        "target_1y": 260.0, "target_3y": 380.0,
        "risk_reward": 2.3, "rr_note": "טוב",
        "buy_signals": ["מעל MA50 וMA200", "MACD חיובי", "AWS margins expanding"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "💡 AMZN — הסיפור עכשיו הוא AWS ו-AI, לא retail. שינוי narrative = הזדמנות.",
        "alt_data": {"insider": {"signal": "⚪ ניטרלי", "buy_count_30d": 1, "cluster_buying": False, "ceo_buying": False, "any_buy": True, "insider_score": 6.0}, "jobs": {"signal": "🟢 מגייסת AI", "hiring_signals_found": 10, "job_trend_score": 8.5}, "web_momentum": {"signal": "🟢 חיובי", "news_count_7d": 25, "positive_headlines": 20, "negative_headlines": 3, "web_momentum_score": 8.0}, "alt_data_score": 7.5},
        "darvas": {"signal": "📦 Consolidation", "darvas_box_top": 225.0, "darvas_box_bottom": 195.0, "in_box": True, "near_breakout": True, "confirmed_breakout": False, "box_tightness_pct": 13.3, "darvas_score": 7.0},
        "squeeze": {"signal": "⏳ Squeeze ניטרלי", "squeeze_active": False, "bw_percentile": 38.0, "breakout_direction": "⏳ Pending", "squeeze_score": 6.5},
        "price_history_30d": [195,198,200,203,206,208,210,207,204,202,205,208,212,210,207,205,208,211,214,212,210,208,210,212,214,212,210,211,212,210.0],
        "news_headlines": ["Amazon AWS revenue hits $100B run rate in Q1 2026", "Amazon advertising surpasses $60B annually", "AWS Bedrock AI platform gains 10,000 enterprise customers"],
        "dividend_yield": 0.0,
        "buyback_yield": 0.006,
        "capex_pct_revenue": 0.122,
        "rd_pct_revenue": 0.133,
        "why_now_hebrew": "יוני 2026 — AMZN 13% מהשיא. AWS beat estimates Q1 2026 על margins. Andy Jassy מסיים turnaround בsuccessfully. Advertising $60B run rate חדש. כניסה לפני catalyst Q3.",
        "why_now_english": "June 2026 — AMZN 13% off peak. AWS beat on margins Q1 2026. Andy Jassy completing turnaround successfully. Advertising $60B new run rate. Entry ahead of Q3 catalyst.",
        "geopolitical_impact_hebrew": "מלחמת הסחר: Amazon retail חשופה לתעריפים — risk על suppliers סיניים. AWS: ממשלות אירופה ומזרח התיכון מגדילות cloud spending. ביטחון לאומי: AWS GovCloud מרוויחה מהגדלת תקציבי ביטחון.",
        "entry_reasoning_hebrew": "כניסה $195-210 — MA200 support. P/E Forward 32x = הוגן. Stop $169 = 52w low. Target $380 ב-3 שנים = CAGR 22%.",
    },
    {
        "ticker": "NEE",
        "company_name": "NextEra Energy, Inc.",
        "sector": "Utilities",
        "industry": "Clean Energy",
        "current_price": 75.0,
        "price_52w_high": 88.0,
        "price_52w_low": 58.0,
        "pct_from_52w_high": -14.8,
        "pct_from_ath": -14.8,
        "price_change_1m_pct": 3.8,
        "price_change_3m_pct": 10.5,
        "market_cap": 154_000_000_000,
        "revenue_ttm": 24_500_000_000,
        "revenue_growth_yoy": 0.10,
        "gross_margin": 0.55,
        "operating_margin": 0.28,
        "net_margin": 0.18,
        "fcf_ttm": -4_200_000_000,
        "fcf_margin": -0.171,
        "roic": 0.065,
        "roe": 0.12,
        "debt_to_equity": 1.55,
        "current_ratio": 0.75,
        "cash": 2_800_000_000,
        "eps_ttm": 3.45,
        "eps_growth_yoy": 0.10,
        "rd_expense": 0,
        "capex": 18_000_000_000,
        "capex_growth_yoy": 0.25,
        "shares_outstanding": 2_050_000_000,
        "shares_change_yoy": 0.02,
        "short_interest_pct": 0.015,
        "short_ratio": 3.5,
        "pe_ttm": 21.7, "pe_forward": 18.5,
        "ps_ratio": 6.3, "pb_ratio": 2.7,
        "ev_ebitda": 18, "peg_ratio": 2.2,
        "analyst_consensus": "buy",
        "analyst_target_mean": 90.0,
        "analyst_target_high": 110.0,
        "analyst_target_low": 70.0,
        "analyst_count": 20,
        "avg_volume_30d": 8_500_000,
        "today_volume": 9_200_000,
        "accruals_ratio": 0.03,
        "earnings_quality": "Medium",
        "earnings_flags": ["⚠️ FCF שלילי — Capex כבד"],
        "quality_score_bonus": 0.0,
        "moat_type": "Wide",
        "moat_sources": ["Regulated utility monopoly — Florida", "Largest clean energy producer in US", "Long-term PPA contracts 15-20 years"],
        "moat_score": 8.5,
        "moat_durability_years": 15,
        "pricing_power": "Regulated",
        "fundamental_score": 7.5,
        "growth_score": 8.0,
        "valuation_score": 8.5,
        "valuation_vs_sector": "Undervalued",
        "dcf_rough_range": "$80-110",
        "multibagger_potential": "Medium",
        "multibagger_reason_hebrew": "AI data centers צורכים חשמל עצום. NEE היא הספקית הגדולה של אנרגיה ירוקה בארה\"ב. כל data center חדש = לקוח חדש ל-NEE.",
        "years_to_potential_peak": "5-8 שנים",
        "key_strengths_hebrew": ["דיבידנד 3.1% — גדל כל שנה", "PPA long-term contracts — הכנסה יציבה", "Data center electricity demand megatrend"],
        "key_risks_hebrew": ["חוב גבוה $1.55 D/E", "FCF שלילי — Capex כבד", "ריבית גבוהה מכבידה על utilities"],
        "growth_drivers_hebrew": ["Solar + Wind expansion", "Data center electricity contracts", "Battery storage grid scale"],
        "sector_verdict_hebrew": "הכי זול ב-utilities הגדולות עם הפוטנציאל הגדול ביותר.",
        "earnings_quality_comment": "FCF שלילי בגלל capex השקעות. נורמלי לutility בצמיחה.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "AI electricity demand מכפיל revenue. Dividend גדל ל-$2.20 ב-2027.",
        "bear_case_hebrew": "ריבית נשארת גבוהה — utilities yield לא אטרקטיבי. CapEx גבוה לוחץ.",
        "psychology_note_hebrew": "NEE — utility שגדלה כמו tech. הכי טוב משני העולמות.",
        "verdict_hebrew": "✅ קנה הדרגתית — data center megatrend + dividend growth.",
        "above_ma50": True, "above_ma200": True,
        "rsi_14": 54.0, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.55,
        "support_1": 70.0, "support_2": 63.0,
        "resistance_1": 82.0, "high_52w": 88.0,
        "volume_ratio": 1.08,
        "technical_score": 7.2,
        "trend": "Bullish",
        "ma20": 73.5, "ma50": 71.2, "ma200": 67.8,
        "basket": "B",
        "aggressive_invest_score": 6.5,
        "intangible_score": 7.5,
        "sentiment_score": 7.8,
        "total_score": 8.3,
        "action": "✅ קנה הדרגתית",
        "action_color": "green",
        "explanation": "Clean energy + data center demand",
        "position_usd": 165,
        "position_note": "$165 — משקל בינוני",
        "dca_plan": ["כניסה ראשונה: $55 עכשיו @ $75", "כניסה שנייה: $55 אם ירד ל-$70", "כניסה שלישית: $55 אם ירד ל-$63"],
        "entry_now": 75.0, "entry_ideal": 70.5, "entry_patient": 63.5,
        "stop_loss": 59.5, "stop_loss_note": "מתחת ל-52w low — צא.",
        "target_1y": 88.0, "target_3y": 115.0,
        "risk_reward": 2.6, "rr_note": "טוב",
        "buy_signals": ["מעל MA50 וMA200", "Dividend 3.1% + growth", "Data center tailwind חזק"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "💡 NEE — utilities שמשמימות? לא כשAI צורכת חשמל כמו עיר שלמה.",
        "alt_data": {"insider": {"signal": "🟢 Cluster Buy", "buy_count_30d": 3, "cluster_buying": True, "ceo_buying": False, "any_buy": True, "insider_score": 7.5}, "jobs": {"signal": "🟢 מגייסת", "hiring_signals_found": 4, "job_trend_score": 7.0}, "web_momentum": {"signal": "⚪ ניטרלי", "news_count_7d": 8, "positive_headlines": 6, "negative_headlines": 1, "web_momentum_score": 7.0}, "alt_data_score": 7.2},
        "darvas": {"signal": "⚡ קרוב לפריצה", "darvas_box_top": 80.0, "darvas_box_bottom": 68.0, "in_box": True, "near_breakout": True, "confirmed_breakout": False, "box_tightness_pct": 14.7, "darvas_score": 7.0},
        "squeeze": {"signal": "⏳ Squeeze ניטרלי", "squeeze_active": False, "bw_percentile": 32.0, "breakout_direction": "⏳ Up", "squeeze_score": 7.0},
        "price_history_30d": [65,66,67,68,69,70,71,70,69,68,70,71,72,73,72,71,72,73,74,73,72,73,74,75,74,74,75,75,74,75.0],
        "news_headlines": ["NextEra signs 5GW data center clean energy deal in 2026", "NEE dividend raised 10% — 29th consecutive year", "NextEra wins Florida grid modernization contract $8B"],
        "dividend_yield": 0.031,
        "buyback_yield": 0.0,
        "capex_pct_revenue": 0.735,
        "rd_pct_revenue": 0.0,
        "why_now_hebrew": "יוני 2026 — NEE עלתה 30% מה-52w low. Data centers סוחרים PPA contracts לאנרגיה ירוקה. הפד צפוי להוריד ריבית H2 2026 — חיובי מאוד ל-utilities dividend stocks.",
        "why_now_english": "June 2026 — NEE up 30% from 52w low. Data centers signing PPA contracts for clean energy. Fed expected to cut rates H2 2026 — very positive for utilities dividend stocks.",
        "geopolitical_impact_hebrew": "ריבית הפד: ירידת ריבית צפויה H2 2026 = utilities מתייקרות (yield comparison). מלחמת הסחר: NEE מייצרת בארה\"ב — אין חשיפה. AI Data Centers: מגה-megatrend ל-NEE. IRA (Inflation Reduction Act): $370B subsidies לאנרגיה ירוקה — NEE הנהנה הגדול.",
        "entry_reasoning_hebrew": "כניסה $70-75 — P/E Forward 18.5x = זול ל-utility צומחת. Dividend yield 3.1% + 10% growth annual = total return ~13%/year. Stop $59.5 = מתחת ל-52w low.",
    },
    {
        "ticker": "JPM",
        "company_name": "JPMorgan Chase & Co.",
        "sector": "Financials",
        "industry": "Banking",
        "current_price": 245.0,
        "price_52w_high": 280.0,
        "price_52w_low": 185.0,
        "pct_from_52w_high": -12.5,
        "pct_from_ath": -12.5,
        "price_change_1m_pct": 4.2,
        "price_change_3m_pct": 9.8,
        "market_cap": 705_000_000_000,
        "revenue_ttm": 162_000_000_000,
        "revenue_growth_yoy": 0.08,
        "gross_margin": 0.62,
        "operating_margin": 0.35,
        "net_margin": 0.24,
        "fcf_ttm": 42_000_000_000,
        "fcf_margin": 0.259,
        "roic": 0.15,
        "roe": 0.18,
        "debt_to_equity": 1.28,
        "current_ratio": 1.2,
        "cash": 500_000_000_000,
        "eps_ttm": 18.90,
        "eps_growth_yoy": 0.08,
        "rd_expense": 15_000_000_000,
        "capex": 6_200_000_000,
        "capex_growth_yoy": 0.08,
        "shares_outstanding": 2_880_000_000,
        "shares_change_yoy": -0.025,
        "short_interest_pct": 0.006,
        "short_ratio": 1.8,
        "pe_ttm": 13.0, "pe_forward": 12.0,
        "ps_ratio": 4.35, "pb_ratio": 2.15,
        "ev_ebitda": 10, "peg_ratio": 1.6,
        "analyst_consensus": "buy",
        "analyst_target_mean": 290.0,
        "analyst_target_high": 330.0,
        "analyst_target_low": 240.0,
        "analyst_count": 26,
        "avg_volume_30d": 10_000_000,
        "today_volume": 11_500_000,
        "accruals_ratio": 0.01,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.5,
        "moat_type": "Wide",
        "moat_sources": ["Too-big-to-fail systemic importance", "Jamie Dimon leadership premium", "Investment banking relationship network"],
        "moat_score": 8.8,
        "moat_durability_years": 20,
        "pricing_power": "Strong",
        "fundamental_score": 8.5,
        "growth_score": 7.5,
        "valuation_score": 9.0,
        "valuation_vs_sector": "Undervalued",
        "dcf_rough_range": "$280-350",
        "multibagger_potential": "Medium",
        "multibagger_reason_hebrew": "JPM הוא הבנק הטוב ביותר בעולם. P/E 12x = cheap. Jamie Dimon מחזיר הון אדיר דרך buybacks ודיבידנד. צמיחה יציבה ב-net interest income.",
        "years_to_potential_peak": "3-5 שנים",
        "key_strengths_hebrew": ["P/E 12 = זול מאוד לבנק הכי טוב בעולם", "Dividend 2.2% + buybacks $15B/שנה", "Jamie Dimon — המנכ\"ל הטוב ביותר בפיננסים"],
        "key_risks_hebrew": ["ריבית יורדת = net interest margin נחתך", "סיכון אשראי במיתון", "רגולציה בנקאית הדוקה יותר"],
        "growth_drivers_hebrew": ["Investment banking recovery", "Consumer credit expansion", "AI in financial services"],
        "sector_verdict_hebrew": "הכי זול מבין הבנקים הגדולים. P/B 2.15x = הוגן מאוד.",
        "earnings_quality_comment": "ROE 18% — מעולה לבנק. FCF $42B. Buybacks $15B/שנה.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "ריבית יורדת — creditmarkets נפתחים. M&A boom חדש. JPM מכפיל EPS.",
        "bear_case_hebrew": "מיתון = loan defaults. Net interest income נחתך. Dimon פורש.",
        "psychology_note_hebrew": "JPM — הבנק שכולם מפחדים לקנות אחרי 2008. אבל 2026 זה אחר.",
        "verdict_hebrew": "✅ קנה — P/E 12 + Dividend 2.2% + Buybacks = total return 15%/year.",
        "above_ma50": True, "above_ma200": True,
        "rsi_14": 56.5, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.60,
        "support_1": 230.0, "support_2": 215.0,
        "resistance_1": 265.0, "high_52w": 280.0,
        "volume_ratio": 1.15,
        "technical_score": 7.5,
        "trend": "Bullish",
        "ma20": 240.0, "ma50": 232.0, "ma200": 218.0,
        "basket": "B",
        "aggressive_invest_score": 7.0,
        "intangible_score": 8.0,
        "sentiment_score": 7.5,
        "total_score": 8.0,
        "action": "✅ קנה עכשיו",
        "action_color": "green",
        "explanation": "P/E 12 + Dividend + Jamie Dimon",
        "position_usd": 155,
        "position_note": "$155 — משקל בינוני-גבוה",
        "dca_plan": ["כניסה ראשונה: $52 עכשיו @ $245", "כניסה שנייה: $52 אם ירד ל-$230", "כניסה שלישית: $51 אם ירד ל-$215"],
        "entry_now": 245.0, "entry_ideal": 230.0, "entry_patient": 216.0,
        "stop_loss": 205.0, "stop_loss_note": "מתחת ל-$205 — צא.",
        "target_1y": 285.0, "target_3y": 380.0,
        "risk_reward": 2.0, "rr_note": "טוב",
        "buy_signals": ["P/E 12 = הכי זול בשנים", "Buybacks $15B/שנה = 2.1% yield", "מעל MA50 וMA200"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "💡 JPM — בנק ה-'boring billionaire'. 13 שנות עלייה רצופה כמעט.",
        "alt_data": {"insider": {"signal": "🟢 CEO Buy", "buy_count_30d": 2, "cluster_buying": True, "ceo_buying": True, "any_buy": True, "insider_score": 8.5}, "jobs": {"signal": "🟢 מגייסת AI FinTech", "hiring_signals_found": 5, "job_trend_score": 7.5}, "web_momentum": {"signal": "🟢 חיובי", "news_count_7d": 12, "positive_headlines": 9, "negative_headlines": 2, "web_momentum_score": 7.5}, "alt_data_score": 7.8},
        "darvas": {"signal": "📦 Consolidation", "darvas_box_top": 260.0, "darvas_box_bottom": 228.0, "in_box": True, "near_breakout": False, "confirmed_breakout": False, "box_tightness_pct": 12.5, "darvas_score": 6.5},
        "squeeze": {"signal": "⏳ Squeeze ניטרלי", "squeeze_active": False, "bw_percentile": 42.0, "breakout_direction": "⏳ Pending", "squeeze_score": 6.0},
        "price_history_30d": [228,230,232,235,238,240,242,240,238,235,238,241,244,242,240,238,241,244,246,244,242,244,246,248,246,244,246,247,246,245.0],
        "news_headlines": ["JPMorgan beats Q1 2026 earnings on investment banking surge", "Jamie Dimon warns of economic turbulence but JPM well-positioned", "JPM announces additional $15B share buyback program"],
        "dividend_yield": 0.022,
        "buyback_yield": 0.021,
        "capex_pct_revenue": 0.038,
        "rd_pct_revenue": 0.093,
        "why_now_hebrew": "יוני 2026 — JPM 12% מהשיא, P/E 12x = הזדמנות נדירה. Jamie Dimon קנה מניות אישית Q1 2026. ריבית הפד צפויה לרדת H2 2026 — credit cycle מתרחב. M&A boom מתחיל.",
        "why_now_english": "June 2026 — JPM 12% off peak, P/E 12x = rare opportunity. Jamie Dimon personally bought shares Q1 2026. Fed expected to cut H2 2026 — credit cycle expanding. M&A boom starting.",
        "geopolitical_impact_hebrew": "מלחמת הסחר: JPM מייעץ לחברות בterriff navigation — revenue מ-advisory. אוקראינה: European reconstruction bonds — JPM underwriter מוביל. ריבית הפד: ירידה = credit expansion = JPM מרוויחה. AI בפיננסים: JPM מוביל עם $15B השקעה ב-AI.",
        "entry_reasoning_hebrew": "כניסה $230-245. P/B 2.15x = הוגן. Dividend 2.2% + Buyback 2.1% = 4.3% base return. Target $380 ב-3 שנים = CAGR 16%.",
    },
    {
        "ticker": "RTX",
        "company_name": "RTX Corporation (Raytheon)",
        "sector": "Industrials",
        "industry": "Defense & Aerospace",
        "current_price": 130.0,
        "price_52w_high": 148.0,
        "price_52w_low": 98.0,
        "pct_from_52w_high": -12.2,
        "pct_from_ath": -12.2,
        "price_change_1m_pct": 3.5,
        "price_change_3m_pct": 12.8,
        "market_cap": 172_000_000_000,
        "revenue_ttm": 80_000_000_000,
        "revenue_growth_yoy": 0.10,
        "gross_margin": 0.18,
        "operating_margin": 0.10,
        "net_margin": 0.075,
        "fcf_ttm": 5_800_000_000,
        "fcf_margin": 0.073,
        "roic": 0.08,
        "roe": 0.145,
        "debt_to_equity": 0.78,
        "current_ratio": 1.2,
        "cash": 7_200_000_000,
        "eps_ttm": 5.25,
        "eps_growth_yoy": 0.15,
        "rd_expense": 3_200_000_000,
        "capex": 2_100_000_000,
        "capex_growth_yoy": 0.12,
        "shares_outstanding": 1_320_000_000,
        "shares_change_yoy": -0.02,
        "short_interest_pct": 0.012,
        "short_ratio": 2.5,
        "pe_ttm": 24.8, "pe_forward": 21.0,
        "ps_ratio": 2.15, "pb_ratio": 3.6,
        "ev_ebitda": 16, "peg_ratio": 1.7,
        "analyst_consensus": "buy",
        "analyst_target_mean": 165.0,
        "analyst_target_high": 195.0,
        "analyst_target_low": 130.0,
        "analyst_count": 18,
        "avg_volume_30d": 4_200_000,
        "today_volume": 4_800_000,
        "accruals_ratio": 0.02,
        "earnings_quality": "High",
        "earnings_flags": [],
        "quality_score_bonus": 0.3,
        "moat_type": "Wide",
        "moat_sources": ["Defense contracts monopoly — classified systems", "Pratt & Whitney engine aftermarket", "Long-term government procurement relationships"],
        "moat_score": 8.5,
        "moat_durability_years": 20,
        "pricing_power": "Strong",
        "fundamental_score": 7.8,
        "growth_score": 8.0,
        "valuation_score": 8.5,
        "valuation_vs_sector": "Undervalued",
        "dcf_rough_range": "$155-200",
        "multibagger_potential": "Medium",
        "multibagger_reason_hebrew": "NATO רחימה + אוקראינה + מתח מזרח תיכוני = supercycle הגנה. RTX ספקית Patriot missiles, F-35 engines. תקציבי ביטחון בכל מדינה עולים.",
        "years_to_potential_peak": "3-6 שנים",
        "key_strengths_hebrew": ["Patriot missile system — demand אדיר מאוקראינה/אירופה", "Pratt & Whitney — aftermarket revenue יציב", "Dividend 2% + buybacks $5B/שנה"],
        "key_risks_hebrew": ["תלות בתקציבי ממשלה", "GTF engine issue — עלויות גבוהות", "Israel/Gaza — פוליטיקלי sensitive"],
        "growth_drivers_hebrew": ["NATO 2% GDP pledge enforcement", "Ukraine reconstruction arms", "Hypersonic missile defense"],
        "sector_verdict_hebrew": "זול ביחס לתעשיית הביטחון. P/E 21 Forward עם 15% EPS growth.",
        "earnings_quality_comment": "FCF $5.8B יציב. Backlog $200B+ — visibility מצוינת.",
        "short_squeeze_potential": False,
        "bull_case_hebrew": "NATO מגדיל הוצאות ביטחון ל-3% GDP. RTX מקבלת contracts ב-$50B+.",
        "bear_case_hebrew": "שלום באוקראינה מקטין demand. GTF engine recall מוחץ margins.",
        "psychology_note_hebrew": "RTX — defense stocks לא sexy. אבל geopolitics 2026 הם bullish מאוד.",
        "verdict_hebrew": "✅ קנה — defense supercycle + dividend + backlog $200B.",
        "above_ma50": True, "above_ma200": True,
        "rsi_14": 56.0, "rsi_signal": "Neutral",
        "macd_bullish": True, "bb_pct": 0.58,
        "support_1": 122.0, "support_2": 112.0,
        "resistance_1": 140.0, "high_52w": 148.0,
        "volume_ratio": 1.14,
        "technical_score": 7.5,
        "trend": "Bullish",
        "ma20": 127.0, "ma50": 122.0, "ma200": 112.0,
        "basket": "B",
        "aggressive_invest_score": 7.0,
        "intangible_score": 7.5,
        "sentiment_score": 8.0,
        "total_score": 8.2,
        "action": "✅ קנה עכשיו",
        "action_color": "green",
        "explanation": "Defense supercycle + dividend + cheap valuation",
        "position_usd": 160,
        "position_note": "$160 — משקל בינוני",
        "dca_plan": ["כניסה ראשונה: $55 עכשיו @ $130", "כניסה שנייה: $55 אם ירד ל-$122", "כניסה שלישית: $50 אם ירד ל-$112"],
        "entry_now": 130.0, "entry_ideal": 122.0, "entry_patient": 113.0,
        "stop_loss": 107.0, "stop_loss_note": "מתחת ל-$107 — צא.",
        "target_1y": 155.0, "target_3y": 210.0,
        "risk_reward": 2.2, "rr_note": "טוב",
        "buy_signals": ["מעל MA50 וMA200 — Bullish", "Backlog $200B+ — visibility חזקה", "NATO spending trend"],
        "sell_signals": [],
        "wait_signals": [],
        "psychology_note": "💡 RTX — 'boring defense'. Boring = predictable = great investment.",
        "alt_data": {"insider": {"signal": "🟢 Cluster Buy", "buy_count_30d": 3, "cluster_buying": True, "ceo_buying": False, "any_buy": True, "insider_score": 7.5}, "jobs": {"signal": "🟢 מגייסת ביטחון", "hiring_signals_found": 6, "job_trend_score": 8.0}, "web_momentum": {"signal": "🟢 חיובי מאוד", "news_count_7d": 15, "positive_headlines": 12, "negative_headlines": 2, "web_momentum_score": 8.0}, "alt_data_score": 7.8},
        "darvas": {"signal": "⚡ פריצה ממתנת", "darvas_box_top": 138.0, "darvas_box_bottom": 118.0, "in_box": True, "near_breakout": True, "confirmed_breakout": False, "box_tightness_pct": 14.5, "darvas_score": 7.5},
        "squeeze": {"signal": "🔥 Squeeze מתהדק", "squeeze_active": True, "bw_percentile": 15.0, "breakout_direction": "🟢 Up", "squeeze_score": 8.0},
        "price_history_30d": [115,118,120,122,124,126,128,126,124,122,124,126,128,130,128,126,128,130,132,130,128,130,132,134,132,130,131,132,131,130.0],
        "news_headlines": ["RTX wins $12B Patriot missile contract from Poland and Germany", "Pratt & Whitney engine backlog hits record $100B", "NATO defense spending hits 2% GDP threshold — RTX primary beneficiary"],
        "dividend_yield": 0.020,
        "buyback_yield": 0.029,
        "capex_pct_revenue": 0.026,
        "rd_pct_revenue": 0.040,
        "why_now_hebrew": "יוני 2026 — RTX עלתה 32% מה-52w low. מלחמת אוקראינה ממשיכה — Patriot demand אדיר. NATO summit יולי 2026 צפוי להכריז על הגדלת תקציבים. Squeeze טכני פעיל.",
        "why_now_english": "June 2026 — RTX up 32% from 52w low. Ukraine war continues — Patriot demand enormous. NATO summit July 2026 expected to announce budget increases. Technical squeeze active.",
        "geopolitical_impact_hebrew": "אוקראינה: RTX מספקת Patriot missiles — demand הולך וגדל. NATO רחימה: 31 מדינות מגדילות תקציב ל-2%+ GDP. מזרח התיכון: ישראל-חמאס — Patriot ו-Iron Dome components. מלחמת הסחר: defense stocks חסינים מתעריפים — US only supply.",
        "entry_reasoning_hebrew": "כניסה $122-130. P/E Forward 21x הוגן לdefense. Backlog $200B = 2.5 שנות revenue מכוסות. Stop $107. Target $210 ב-3 שנים = CAGR 17%.",
    },
]

DEMO_STOCKS.sort(key=lambda s: s.get("total_score", 0), reverse=True)

DEMO_WATCHLIST_EXTRA = ["GOOG", "META", "QQQ", "AMD", "PLTR", "QUBT", "XOVR"]

DEMO_PORTFOLIO = {
    "positions": [
        {"ticker": "GOOG",  "price": 182.5,  "score": 7.8, "trend": "Bullish", "pct_from_ath": -11.2, "above_ma200": True,  "rsi_14": 54.2, "action": "✅ המשך להחזיק — חזק", "avg_cost": 155.0, "pnl_pct": 17.7, "ret_7d": 1.2, "ret_30d": 3.5, "ret_90d": 8.1, "ret_365d": 22.4, "date": "2024-01-15", "price_at_rec": 160.0, "lower": 170.0},
        {"ticker": "NVDA",  "price": 118.5,  "score": 8.4, "trend": "Bullish", "pct_from_ath": -22.6, "above_ma200": True,  "rsi_14": 58.2, "action": "✅ המשך להחזיק — חזק", "avg_cost": 95.0,  "pnl_pct": 24.7, "ret_7d": 2.1, "ret_30d": 5.8, "ret_90d": 14.2, "ret_365d": 45.1, "date": "2024-02-10", "price_at_rec": 100.0, "lower": 110.0},
        {"ticker": "META",  "price": 642.0,  "score": 8.1, "trend": "Bullish", "pct_from_ath": -5.8,  "above_ma200": True,  "rsi_14": 61.0, "action": "✅ המשך להחזיק — חזק", "avg_cost": 520.0, "pnl_pct": 23.5, "ret_7d": 0.8, "ret_30d": 2.9, "ret_90d": 9.5, "ret_365d": 38.2, "date": "2024-03-05", "price_at_rec": 530.0, "lower": 610.0},
        {"ticker": "QQQ",   "price": 487.0,  "score": 7.2, "trend": "Bullish", "pct_from_ath": -8.1,  "above_ma200": True,  "rsi_14": 55.5, "action": "⏳ החזק — עדיין סביר",  "avg_cost": 450.0, "pnl_pct": 8.2,  "ret_7d": 0.6, "ret_30d": 1.8, "ret_90d": 5.2, "ret_365d": 18.5, "date": "2024-01-20", "price_at_rec": 455.0, "lower": 475.0},
        {"ticker": "AMD",   "price": 118.0,  "score": 6.9, "trend": "Mixed",   "pct_from_ath": -41.5, "above_ma200": False, "rsi_14": 47.3, "action": "👀 עקוב",                "avg_cost": 140.0, "pnl_pct": -15.7,"ret_7d": -1.1,"ret_30d": -3.2,"ret_90d": -8.8,"ret_365d": -12.5,"date": "2024-04-01","price_at_rec": 145.0,"lower": 115.0},
        {"ticker": "PLTR",  "price": 118.0,  "score": 7.5, "trend": "Bullish", "pct_from_ath": -12.3, "above_ma200": True,  "rsi_14": 62.1, "action": "✅ המשך להחזיק — חזק", "avg_cost": 90.0,  "pnl_pct": 31.1, "ret_7d": 1.5, "ret_30d": 4.2, "ret_90d": 18.3, "ret_365d": 62.0, "date": "2024-02-20", "price_at_rec": 92.0, "lower": 110.0},
        {"ticker": "QUBT",  "price": 8.25,   "score": 5.8, "trend": "Bearish", "pct_from_ath": -68.0, "above_ma200": False, "rsi_14": 35.1, "action": "⚠️ שקול לצמצם",         "avg_cost": 18.0,  "pnl_pct": -54.2,"ret_7d": -2.5,"ret_30d": -8.1,"ret_90d": -25.0,"ret_365d": -55.0,"date": "2024-05-01","price_at_rec": 20.0,"lower": 9.0},
        {"ticker": "XOVR",  "price": 2.10,   "score": 4.2, "trend": "Bearish", "pct_from_ath": -82.0, "above_ma200": False, "rsi_14": 28.4, "action": "⚠️ שקול לצמצם",         "avg_cost": 8.0,   "pnl_pct": -73.8,"ret_7d": -3.2,"ret_30d": -12.0,"ret_90d": -38.0,"ret_365d": -72.0,"date": "2024-06-01","price_at_rec": 9.0,"lower": 3.0},
    ],
    "total_stocks": 8,
    "total_pnl_usd": 4250.0,
    "total_pnl_pct": 12.3,
    "total_current_value": 38750.0,
    "total_invested": 34500.0,
}

DEMO_MACRO = {
    "macro": {
        "SPY":      {"name": "S&P 500",     "price": 548.2, "chg_1d": 0.42, "chg_1w": 1.18},
        "QQQ":      {"name": "Nasdaq",      "price": 487.0, "chg_1d": 0.61, "chg_1w": 1.52},
        "^VIX":     {"name": "VIX פחד",     "price": 17.8,  "chg_1d": -3.20, "chg_1w": -8.50},
        "DX-Y.NYB": {"name": "דולר DXY",    "price": 104.2, "chg_1d": 0.05,  "chg_1w": 0.22},
        "TLT":      {"name": "אג\"ח ארוך", "price": 91.4,  "chg_1d": 0.18,  "chg_1w": -0.40},
        "GLD":      {"name": "זהב",         "price": 2305.0,"chg_1d": -0.22, "chg_1w": 0.85},
    },
    "regime": {
        "regime": "NORMAL",
        "hebrew": "שוק רגיל — VIX 17.8",
        "action": "📊 עבוד לפי האלגוריתם הרגיל",
        "color": "blue",
        "weight_adjustment": {},
    }
}
